// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: apis/serviceconn/gateway_discussion/pb/gw_discussion.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscussionService_CreateDiscussion_FullMethodName  = "/discussion_svc.DiscussionService/CreateDiscussion"
	DiscussionService_ListDiscussions_FullMethodName   = "/discussion_svc.DiscussionService/ListDiscussions"
	DiscussionService_GetDiscussion_FullMethodName     = "/discussion_svc.DiscussionService/GetDiscussion"
	DiscussionService_ReplyToDiscussion_FullMethodName = "/discussion_svc.DiscussionService/ReplyToDiscussion"
	DiscussionService_LikeDiscussion_FullMethodName    = "/discussion_svc.DiscussionService/LikeDiscussion"
	DiscussionService_EditDiscussion_FullMethodName    = "/discussion_svc.DiscussionService/EditDiscussion"
	DiscussionService_DeleteDiscussion_FullMethodName  = "/discussion_svc.DiscussionService/DeleteDiscussion"
)

// DiscussionServiceClient is the client API for DiscussionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscussionServiceClient interface {
	CreateDiscussion(ctx context.Context, in *CreateDiscussionReq, opts ...grpc.CallOption) (*DiscussionResp, error)
	ListDiscussions(ctx context.Context, in *ListDiscussionsReq, opts ...grpc.CallOption) (*ListDiscussionsResp, error)
	GetDiscussion(ctx context.Context, in *DiscussionActionReq, opts ...grpc.CallOption) (*DiscussionResp, error)
	ReplyToDiscussion(ctx context.Context, in *ReplyDiscussionReq, opts ...grpc.CallOption) (*ReplyDiscussionResp, error)
	LikeDiscussion(ctx context.Context, in *DiscussionActionReq, opts ...grpc.CallOption) (*LikeDiscussionResp, error)
	EditDiscussion(ctx context.Context, in *EditDiscussionReq, opts ...grpc.CallOption) (*DiscussionResp, error)
	DeleteDiscussion(ctx context.Context, in *DiscussionActionReq, opts ...grpc.CallOption) (*DiscussionResp, error)
}

type discussionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscussionServiceClient(cc grpc.ClientConnInterface) DiscussionServiceClient {
	return &discussionServiceClient{cc}
}

func (c *discussionServiceClient) CreateDiscussion(ctx context.Context, in *CreateDiscussionReq, opts ...grpc.CallOption) (*DiscussionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscussionResp)
	err := c.cc.Invoke(ctx, DiscussionService_CreateDiscussion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) ListDiscussions(ctx context.Context, in *ListDiscussionsReq, opts ...grpc.CallOption) (*ListDiscussionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiscussionsResp)
	err := c.cc.Invoke(ctx, DiscussionService_ListDiscussions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) GetDiscussion(ctx context.Context, in *DiscussionActionReq, opts ...grpc.CallOption) (*DiscussionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscussionResp)
	err := c.cc.Invoke(ctx, DiscussionService_GetDiscussion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) ReplyToDiscussion(ctx context.Context, in *ReplyDiscussionReq, opts ...grpc.CallOption) (*ReplyDiscussionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyDiscussionResp)
	err := c.cc.Invoke(ctx, DiscussionService_ReplyToDiscussion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) LikeDiscussion(ctx context.Context, in *DiscussionActionReq, opts ...grpc.CallOption) (*LikeDiscussionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeDiscussionResp)
	err := c.cc.Invoke(ctx, DiscussionService_LikeDiscussion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) EditDiscussion(ctx context.Context, in *EditDiscussionReq, opts ...grpc.CallOption) (*DiscussionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscussionResp)
	err := c.cc.Invoke(ctx, DiscussionService_EditDiscussion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discussionServiceClient) DeleteDiscussion(ctx context.Context, in *DiscussionActionReq, opts ...grpc.CallOption) (*DiscussionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscussionResp)
	err := c.cc.Invoke(ctx, DiscussionService_DeleteDiscussion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscussionServiceServer is the server API for DiscussionService service.
// All implementations must embed UnimplementedDiscussionServiceServer
// for forward compatibility.
type DiscussionServiceServer interface {
	CreateDiscussion(context.Context, *CreateDiscussionReq) (*DiscussionResp, error)
	ListDiscussions(context.Context, *ListDiscussionsReq) (*ListDiscussionsResp, error)
	GetDiscussion(context.Context, *DiscussionActionReq) (*DiscussionResp, error)
	ReplyToDiscussion(context.Context, *ReplyDiscussionReq) (*ReplyDiscussionResp, error)
	LikeDiscussion(context.Context, *DiscussionActionReq) (*LikeDiscussionResp, error)
	EditDiscussion(context.Context, *EditDiscussionReq) (*DiscussionResp, error)
	DeleteDiscussion(context.Context, *DiscussionActionReq) (*DiscussionResp, error)
	mustEmbedUnimplementedDiscussionServiceServer()
}

// UnimplementedDiscussionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscussionServiceServer struct{}

func (UnimplementedDiscussionServiceServer) CreateDiscussion(context.Context, *CreateDiscussionReq) (*DiscussionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDiscussion not implemented")
}
func (UnimplementedDiscussionServiceServer) ListDiscussions(context.Context, *ListDiscussionsReq) (*ListDiscussionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDiscussions not implemented")
}
func (UnimplementedDiscussionServiceServer) GetDiscussion(context.Context, *DiscussionActionReq) (*DiscussionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiscussion not implemented")
}
func (UnimplementedDiscussionServiceServer) ReplyToDiscussion(context.Context, *ReplyDiscussionReq) (*ReplyDiscussionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplyToDiscussion not implemented")
}
func (UnimplementedDiscussionServiceServer) LikeDiscussion(context.Context, *DiscussionActionReq) (*LikeDiscussionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeDiscussion not implemented")
}
func (UnimplementedDiscussionServiceServer) EditDiscussion(context.Context, *EditDiscussionReq) (*DiscussionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EditDiscussion not implemented")
}
func (UnimplementedDiscussionServiceServer) DeleteDiscussion(context.Context, *DiscussionActionReq) (*DiscussionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDiscussion not implemented")
}
func (UnimplementedDiscussionServiceServer) mustEmbedUnimplementedDiscussionServiceServer() {}
func (UnimplementedDiscussionServiceServer) testEmbeddedByValue()                           {}

// UnsafeDiscussionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscussionServiceServer will
// result in compilation errors.
type UnsafeDiscussionServiceServer interface {
	mustEmbedUnimplementedDiscussionServiceServer()
}

func RegisterDiscussionServiceServer(s grpc.ServiceRegistrar, srv DiscussionServiceServer) {
	// If the following call panics, it indicates UnimplementedDiscussionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscussionService_ServiceDesc, srv)
}

func _DiscussionService_CreateDiscussion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiscussionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).CreateDiscussion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_CreateDiscussion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).CreateDiscussion(ctx, req.(*CreateDiscussionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_ListDiscussions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiscussionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).ListDiscussions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_ListDiscussions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).ListDiscussions(ctx, req.(*ListDiscussionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_GetDiscussion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscussionActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).GetDiscussion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_GetDiscussion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).GetDiscussion(ctx, req.(*DiscussionActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_ReplyToDiscussion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyDiscussionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).ReplyToDiscussion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_ReplyToDiscussion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).ReplyToDiscussion(ctx, req.(*ReplyDiscussionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_LikeDiscussion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscussionActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).LikeDiscussion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_LikeDiscussion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).LikeDiscussion(ctx, req.(*DiscussionActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_EditDiscussion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditDiscussionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).EditDiscussion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_EditDiscussion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).EditDiscussion(ctx, req.(*EditDiscussionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscussionService_DeleteDiscussion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscussionActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscussionServiceServer).DeleteDiscussion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscussionService_DeleteDiscussion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscussionServiceServer).DeleteDiscussion(ctx, req.(*DiscussionActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscussionService_ServiceDesc is the grpc.ServiceDesc for DiscussionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscussionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discussion_svc.DiscussionService",
	HandlerType: (*DiscussionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDiscussion",
			Handler:    _DiscussionService_CreateDiscussion_Handler,
		},
		{
			MethodName: "ListDiscussions",
			Handler:    _DiscussionService_ListDiscussions_Handler,
		},
		{
			MethodName: "GetDiscussion",
			Handler:    _DiscussionService_GetDiscussion_Handler,
		},
		{
			MethodName: "ReplyToDiscussion",
			Handler:    _DiscussionService_ReplyToDiscussion_Handler,
		},
		{
			MethodName: "LikeDiscussion",
			Handler:    _DiscussionService_LikeDiscussion_Handler,
		},
		{
			MethodName: "EditDiscussion",
			Handler:    _DiscussionService_EditDiscussion_Handler,
		},
		{
			MethodName: "DeleteDiscussion",
			Handler:    _DiscussionService_DeleteDiscussion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis/serviceconn/gateway_discussion/pb/gw_discussion.proto",
}
