// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: apis/serviceconn/gateway_user/pb/gw_user.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetUserActivities_FullMethodName           = "/auth_svc.UserService/GetUserActivities"
	UserService_GetUserProfile_FullMethodName              = "/auth_svc.UserService/GetUserProfile"
	UserService_UpdateUserProfile_FullMethodName           = "/auth_svc.UserService/UpdateUserProfile"
	UserService_DeleteUserAccount_FullMethodName           = "/auth_svc.UserService/DeleteUserAccount"
	UserService_GetAllTopics_FullMethodName                = "/auth_svc.UserService/GetAllTopics"
	UserService_GetAllCategories_FullMethodName            = "/auth_svc.UserService/GetAllCategories"
	UserService_GetUserDetails_FullMethodName              = "/auth_svc.UserService/GetUserDetails"
	UserService_FollowTopics_FullMethodName                = "/auth_svc.UserService/FollowTopics"
	UserService_UnFollowTopics_FullMethodName              = "/auth_svc.UserService/UnFollowTopics"
	UserService_FollowUser_FullMethodName                  = "/auth_svc.UserService/FollowUser"
	UserService_UnFollowUser_FullMethodName                = "/auth_svc.UserService/UnFollowUser"
	UserService_GetFollowers_FullMethodName                = "/auth_svc.UserService/GetFollowers"
	UserService_GetFollowing_FullMethodName                = "/auth_svc.UserService/GetFollowing"
	UserService_GetIfIFollowedUser_FullMethodName          = "/auth_svc.UserService/GetIfIFollowedUser"
	UserService_GetFollowersFollowingCounts_FullMethodName = "/auth_svc.UserService/GetFollowersFollowingCounts"
	UserService_SearchUser_FullMethodName                  = "/auth_svc.UserService/SearchUser"
	UserService_BookMarkBlog_FullMethodName                = "/auth_svc.UserService/BookMarkBlog"
	UserService_GetBookMarks_FullMethodName                = "/auth_svc.UserService/GetBookMarks"
	UserService_RemoveBookMark_FullMethodName              = "/auth_svc.UserService/RemoveBookMark"
	UserService_LikeBlog_FullMethodName                    = "/auth_svc.UserService/LikeBlog"
	UserService_UnlikeBlog_FullMethodName                  = "/auth_svc.UserService/UnlikeBlog"
	UserService_GetIfBlogLiked_FullMethodName              = "/auth_svc.UserService/GetIfBlogLiked"
	UserService_GetIfBlogBookMarked_FullMethodName         = "/auth_svc.UserService/GetIfBlogBookMarked"
	UserService_GetBookMarkCounts_FullMethodName           = "/auth_svc.UserService/GetBookMarkCounts"
	UserService_GetLikeCounts_FullMethodName               = "/auth_svc.UserService/GetLikeCounts"
	UserService_InviteCoAuthor_FullMethodName              = "/auth_svc.UserService/InviteCoAuthor"
	UserService_RevokeCoAuthorAccess_FullMethodName        = "/auth_svc.UserService/RevokeCoAuthorAccess"
	UserService_GetBlogsByUserIds_FullMethodName           = "/auth_svc.UserService/GetBlogsByUserIds"
	UserService_CreateNewTopics_FullMethodName             = "/auth_svc.UserService/CreateNewTopics"
	UserService_GetBatchUserDetails_FullMethodName         = "/auth_svc.UserService/GetBatchUserDetails"
	UserService_CreateBusinessCard_FullMethodName          = "/auth_svc.UserService/CreateBusinessCard"
	UserService_GetBusinessCard_FullMethodName             = "/auth_svc.UserService/GetBusinessCard"
	UserService_ListBusinessCards_FullMethodName           = "/auth_svc.UserService/ListBusinessCards"
	UserService_UpdateBusinessCard_FullMethodName          = "/auth_svc.UserService/UpdateBusinessCard"
	UserService_DeleteBusinessCard_FullMethodName          = "/auth_svc.UserService/DeleteBusinessCard"
	UserService_CreateUserAddress_FullMethodName           = "/auth_svc.UserService/CreateUserAddress"
	UserService_GetUserAddress_FullMethodName              = "/auth_svc.UserService/GetUserAddress"
	UserService_ListUserAddresses_FullMethodName           = "/auth_svc.UserService/ListUserAddresses"
	UserService_UpdateUserAddress_FullMethodName           = "/auth_svc.UserService/UpdateUserAddress"
	UserService_DeleteUserAddress_FullMethodName           = "/auth_svc.UserService/DeleteUserAddress"
	UserService_SubmitVerificationRequest_FullMethodName   = "/auth_svc.UserService/SubmitVerificationRequest"
	UserService_GetMyVerification_FullMethodName           = "/auth_svc.UserService/GetMyVerification"
	UserService_CancelVerificationRequest_FullMethodName   = "/auth_svc.UserService/CancelVerificationRequest"
	UserService_ListVerificationRequests_FullMethodName    = "/auth_svc.UserService/ListVerificationRequests"
	UserService_ReviewVerificationRequest_FullMethodName   = "/auth_svc.UserService/ReviewVerificationRequest"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUserActivities(ctx context.Context, in *UserActivityReq, opts ...grpc.CallOption) (*UserActivityResp, error)
	GetUserProfile(ctx context.Context, in *UserProfileReq, opts ...grpc.CallOption) (*UserProfileRes, error)
	UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...grpc.CallOption) (*UpdateUserProfileRes, error)
	DeleteUserAccount(ctx context.Context, in *DeleteUserProfileReq, opts ...grpc.CallOption) (*DeleteUserProfileRes, error)
	GetAllTopics(ctx context.Context, in *GetTopicsRequests, opts ...grpc.CallOption) (*GetTopicsResponse, error)
	GetAllCategories(ctx context.Context, in *GetAllCategoriesReq, opts ...grpc.CallOption) (*GetAllCategoriesRes, error)
	GetUserDetails(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*UserDetailsResp, error)
	FollowTopics(ctx context.Context, in *TopicActionReq, opts ...grpc.CallOption) (*TopicActionRes, error)
	UnFollowTopics(ctx context.Context, in *TopicActionReq, opts ...grpc.CallOption) (*TopicActionRes, error)
	FollowUser(ctx context.Context, in *UserFollowReq, opts ...grpc.CallOption) (*UserFollowRes, error)
	UnFollowUser(ctx context.Context, in *UserFollowReq, opts ...grpc.CallOption) (*UserFollowRes, error)
	GetFollowers(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*FollowerFollowingResp, error)
	GetFollowing(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*FollowerFollowingResp, error)
	GetIfIFollowedUser(ctx context.Context, in *UserFollowReq, opts ...grpc.CallOption) (*UserFollowRes, error)
	GetFollowersFollowingCounts(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*FollowerFollowingCountsResp, error)
	SearchUser(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UserDetailReq, FollowerFollowingResp], error)
	// Bookmark blog
	BookMarkBlog(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error)
	GetBookMarks(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error)
	// Remove Bookmark
	RemoveBookMark(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error)
	LikeBlog(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error)
	UnlikeBlog(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error)
	GetIfBlogLiked(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error)
	GetIfBlogBookMarked(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error)
	GetBookMarkCounts(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*CountResp, error)
	GetLikeCounts(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*CountResp, error)
	// Invite a co author
	InviteCoAuthor(ctx context.Context, in *CoAuthorAccessReq, opts ...grpc.CallOption) (*CoAuthorAccessRes, error)
	// Accept co author invitation
	// Reject co author invitation
	// Revoke co author invitation access
	RevokeCoAuthorAccess(ctx context.Context, in *CoAuthorAccessReq, opts ...grpc.CallOption) (*CoAuthorAccessRes, error)
	GetBlogsByUserIds(ctx context.Context, in *BlogsByUserIdsReq, opts ...grpc.CallOption) (*BlogsByUserNameRes, error)
	CreateNewTopics(ctx context.Context, in *CreateTopicsReq, opts ...grpc.CallOption) (*CreateTopicsRes, error)
	GetBatchUserDetails(ctx context.Context, in *GetBatchUserDetailsReq, opts ...grpc.CallOption) (*GetBatchUserDetailsRes, error)
	// Business Cards (owned by account_id, stored in business_cards table)
	CreateBusinessCard(ctx context.Context, in *CreateBusinessCardReq, opts ...grpc.CallOption) (*BusinessCard, error)
	GetBusinessCard(ctx context.Context, in *GetBusinessCardReq, opts ...grpc.CallOption) (*BusinessCard, error)
	ListBusinessCards(ctx context.Context, in *ListBusinessCardsReq, opts ...grpc.CallOption) (*ListBusinessCardsRes, error)
	UpdateBusinessCard(ctx context.Context, in *UpdateBusinessCardReq, opts ...grpc.CallOption) (*BusinessCard, error)
	DeleteBusinessCard(ctx context.Context, in *DeleteBusinessCardReq, opts ...grpc.CallOption) (*DeleteBusinessCardRes, error)
	// Private addresses (owned by account_id, stored in user_addresses table)
	CreateUserAddress(ctx context.Context, in *CreateUserAddressReq, opts ...grpc.CallOption) (*UserAddress, error)
	GetUserAddress(ctx context.Context, in *GetUserAddressReq, opts ...grpc.CallOption) (*UserAddress, error)
	ListUserAddresses(ctx context.Context, in *ListUserAddressesReq, opts ...grpc.CallOption) (*ListUserAddressesRes, error)
	UpdateUserAddress(ctx context.Context, in *UpdateUserAddressReq, opts ...grpc.CallOption) (*UserAddress, error)
	DeleteUserAddress(ctx context.Context, in *DeleteUserAddressReq, opts ...grpc.CallOption) (*DeleteUserAddressRes, error)
	// Account verification (blue-check)
	SubmitVerificationRequest(ctx context.Context, in *SubmitVerificationReq, opts ...grpc.CallOption) (*VerificationRequest, error)
	GetMyVerification(ctx context.Context, in *GetVerificationReq, opts ...grpc.CallOption) (*VerificationRequest, error)
	CancelVerificationRequest(ctx context.Context, in *GetVerificationReq, opts ...grpc.CallOption) (*VerificationActionRes, error)
	// Admin review surface
	ListVerificationRequests(ctx context.Context, in *ListVerificationReq, opts ...grpc.CallOption) (*ListVerificationRes, error)
	ReviewVerificationRequest(ctx context.Context, in *ReviewVerificationReq, opts ...grpc.CallOption) (*VerificationRequest, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserActivities(ctx context.Context, in *UserActivityReq, opts ...grpc.CallOption) (*UserActivityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserActivityResp)
	err := c.cc.Invoke(ctx, UserService_GetUserActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserProfile(ctx context.Context, in *UserProfileReq, opts ...grpc.CallOption) (*UserProfileRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileRes)
	err := c.cc.Invoke(ctx, UserService_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileReq, opts ...grpc.CallOption) (*UpdateUserProfileRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserProfileRes)
	err := c.cc.Invoke(ctx, UserService_UpdateUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUserAccount(ctx context.Context, in *DeleteUserProfileReq, opts ...grpc.CallOption) (*DeleteUserProfileRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserProfileRes)
	err := c.cc.Invoke(ctx, UserService_DeleteUserAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAllTopics(ctx context.Context, in *GetTopicsRequests, opts ...grpc.CallOption) (*GetTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopicsResponse)
	err := c.cc.Invoke(ctx, UserService_GetAllTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAllCategories(ctx context.Context, in *GetAllCategoriesReq, opts ...grpc.CallOption) (*GetAllCategoriesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllCategoriesRes)
	err := c.cc.Invoke(ctx, UserService_GetAllCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserDetails(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*UserDetailsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDetailsResp)
	err := c.cc.Invoke(ctx, UserService_GetUserDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FollowTopics(ctx context.Context, in *TopicActionReq, opts ...grpc.CallOption) (*TopicActionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicActionRes)
	err := c.cc.Invoke(ctx, UserService_FollowTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UnFollowTopics(ctx context.Context, in *TopicActionReq, opts ...grpc.CallOption) (*TopicActionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicActionRes)
	err := c.cc.Invoke(ctx, UserService_UnFollowTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FollowUser(ctx context.Context, in *UserFollowReq, opts ...grpc.CallOption) (*UserFollowRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserFollowRes)
	err := c.cc.Invoke(ctx, UserService_FollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UnFollowUser(ctx context.Context, in *UserFollowReq, opts ...grpc.CallOption) (*UserFollowRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserFollowRes)
	err := c.cc.Invoke(ctx, UserService_UnFollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFollowers(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*FollowerFollowingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowerFollowingResp)
	err := c.cc.Invoke(ctx, UserService_GetFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFollowing(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*FollowerFollowingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowerFollowingResp)
	err := c.cc.Invoke(ctx, UserService_GetFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetIfIFollowedUser(ctx context.Context, in *UserFollowReq, opts ...grpc.CallOption) (*UserFollowRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserFollowRes)
	err := c.cc.Invoke(ctx, UserService_GetIfIFollowedUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFollowersFollowingCounts(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*FollowerFollowingCountsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowerFollowingCountsResp)
	err := c.cc.Invoke(ctx, UserService_GetFollowersFollowingCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SearchUser(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UserDetailReq, FollowerFollowingResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], UserService_SearchUser_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserDetailReq, FollowerFollowingResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_SearchUserClient = grpc.BidiStreamingClient[UserDetailReq, FollowerFollowingResp]

func (c *userServiceClient) BookMarkBlog(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookMarkRes)
	err := c.cc.Invoke(ctx, UserService_BookMarkBlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetBookMarks(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookMarkRes)
	err := c.cc.Invoke(ctx, UserService_GetBookMarks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveBookMark(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookMarkRes)
	err := c.cc.Invoke(ctx, UserService_RemoveBookMark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LikeBlog(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookMarkRes)
	err := c.cc.Invoke(ctx, UserService_LikeBlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UnlikeBlog(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookMarkRes)
	err := c.cc.Invoke(ctx, UserService_UnlikeBlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetIfBlogLiked(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookMarkRes)
	err := c.cc.Invoke(ctx, UserService_GetIfBlogLiked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetIfBlogBookMarked(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*BookMarkRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookMarkRes)
	err := c.cc.Invoke(ctx, UserService_GetIfBlogBookMarked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetBookMarkCounts(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*CountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResp)
	err := c.cc.Invoke(ctx, UserService_GetBookMarkCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetLikeCounts(ctx context.Context, in *BookMarkReq, opts ...grpc.CallOption) (*CountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResp)
	err := c.cc.Invoke(ctx, UserService_GetLikeCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) InviteCoAuthor(ctx context.Context, in *CoAuthorAccessReq, opts ...grpc.CallOption) (*CoAuthorAccessRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoAuthorAccessRes)
	err := c.cc.Invoke(ctx, UserService_InviteCoAuthor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RevokeCoAuthorAccess(ctx context.Context, in *CoAuthorAccessReq, opts ...grpc.CallOption) (*CoAuthorAccessRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoAuthorAccessRes)
	err := c.cc.Invoke(ctx, UserService_RevokeCoAuthorAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetBlogsByUserIds(ctx context.Context, in *BlogsByUserIdsReq, opts ...grpc.CallOption) (*BlogsByUserNameRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlogsByUserNameRes)
	err := c.cc.Invoke(ctx, UserService_GetBlogsByUserIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateNewTopics(ctx context.Context, in *CreateTopicsReq, opts ...grpc.CallOption) (*CreateTopicsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTopicsRes)
	err := c.cc.Invoke(ctx, UserService_CreateNewTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetBatchUserDetails(ctx context.Context, in *GetBatchUserDetailsReq, opts ...grpc.CallOption) (*GetBatchUserDetailsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatchUserDetailsRes)
	err := c.cc.Invoke(ctx, UserService_GetBatchUserDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateBusinessCard(ctx context.Context, in *CreateBusinessCardReq, opts ...grpc.CallOption) (*BusinessCard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BusinessCard)
	err := c.cc.Invoke(ctx, UserService_CreateBusinessCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetBusinessCard(ctx context.Context, in *GetBusinessCardReq, opts ...grpc.CallOption) (*BusinessCard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BusinessCard)
	err := c.cc.Invoke(ctx, UserService_GetBusinessCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListBusinessCards(ctx context.Context, in *ListBusinessCardsReq, opts ...grpc.CallOption) (*ListBusinessCardsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBusinessCardsRes)
	err := c.cc.Invoke(ctx, UserService_ListBusinessCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateBusinessCard(ctx context.Context, in *UpdateBusinessCardReq, opts ...grpc.CallOption) (*BusinessCard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BusinessCard)
	err := c.cc.Invoke(ctx, UserService_UpdateBusinessCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteBusinessCard(ctx context.Context, in *DeleteBusinessCardReq, opts ...grpc.CallOption) (*DeleteBusinessCardRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBusinessCardRes)
	err := c.cc.Invoke(ctx, UserService_DeleteBusinessCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUserAddress(ctx context.Context, in *CreateUserAddressReq, opts ...grpc.CallOption) (*UserAddress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAddress)
	err := c.cc.Invoke(ctx, UserService_CreateUserAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserAddress(ctx context.Context, in *GetUserAddressReq, opts ...grpc.CallOption) (*UserAddress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAddress)
	err := c.cc.Invoke(ctx, UserService_GetUserAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUserAddresses(ctx context.Context, in *ListUserAddressesReq, opts ...grpc.CallOption) (*ListUserAddressesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserAddressesRes)
	err := c.cc.Invoke(ctx, UserService_ListUserAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserAddress(ctx context.Context, in *UpdateUserAddressReq, opts ...grpc.CallOption) (*UserAddress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAddress)
	err := c.cc.Invoke(ctx, UserService_UpdateUserAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUserAddress(ctx context.Context, in *DeleteUserAddressReq, opts ...grpc.CallOption) (*DeleteUserAddressRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserAddressRes)
	err := c.cc.Invoke(ctx, UserService_DeleteUserAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SubmitVerificationRequest(ctx context.Context, in *SubmitVerificationReq, opts ...grpc.CallOption) (*VerificationRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerificationRequest)
	err := c.cc.Invoke(ctx, UserService_SubmitVerificationRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetMyVerification(ctx context.Context, in *GetVerificationReq, opts ...grpc.CallOption) (*VerificationRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerificationRequest)
	err := c.cc.Invoke(ctx, UserService_GetMyVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CancelVerificationRequest(ctx context.Context, in *GetVerificationReq, opts ...grpc.CallOption) (*VerificationActionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerificationActionRes)
	err := c.cc.Invoke(ctx, UserService_CancelVerificationRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListVerificationRequests(ctx context.Context, in *ListVerificationReq, opts ...grpc.CallOption) (*ListVerificationRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVerificationRes)
	err := c.cc.Invoke(ctx, UserService_ListVerificationRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReviewVerificationRequest(ctx context.Context, in *ReviewVerificationReq, opts ...grpc.CallOption) (*VerificationRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerificationRequest)
	err := c.cc.Invoke(ctx, UserService_ReviewVerificationRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	GetUserActivities(context.Context, *UserActivityReq) (*UserActivityResp, error)
	GetUserProfile(context.Context, *UserProfileReq) (*UserProfileRes, error)
	UpdateUserProfile(context.Context, *UpdateUserProfileReq) (*UpdateUserProfileRes, error)
	DeleteUserAccount(context.Context, *DeleteUserProfileReq) (*DeleteUserProfileRes, error)
	GetAllTopics(context.Context, *GetTopicsRequests) (*GetTopicsResponse, error)
	GetAllCategories(context.Context, *GetAllCategoriesReq) (*GetAllCategoriesRes, error)
	GetUserDetails(context.Context, *UserDetailReq) (*UserDetailsResp, error)
	FollowTopics(context.Context, *TopicActionReq) (*TopicActionRes, error)
	UnFollowTopics(context.Context, *TopicActionReq) (*TopicActionRes, error)
	FollowUser(context.Context, *UserFollowReq) (*UserFollowRes, error)
	UnFollowUser(context.Context, *UserFollowReq) (*UserFollowRes, error)
	GetFollowers(context.Context, *UserDetailReq) (*FollowerFollowingResp, error)
	GetFollowing(context.Context, *UserDetailReq) (*FollowerFollowingResp, error)
	GetIfIFollowedUser(context.Context, *UserFollowReq) (*UserFollowRes, error)
	GetFollowersFollowingCounts(context.Context, *UserDetailReq) (*FollowerFollowingCountsResp, error)
	SearchUser(grpc.BidiStreamingServer[UserDetailReq, FollowerFollowingResp]) error
	// Bookmark blog
	BookMarkBlog(context.Context, *BookMarkReq) (*BookMarkRes, error)
	GetBookMarks(context.Context, *BookMarkReq) (*BookMarkRes, error)
	// Remove Bookmark
	RemoveBookMark(context.Context, *BookMarkReq) (*BookMarkRes, error)
	LikeBlog(context.Context, *BookMarkReq) (*BookMarkRes, error)
	UnlikeBlog(context.Context, *BookMarkReq) (*BookMarkRes, error)
	GetIfBlogLiked(context.Context, *BookMarkReq) (*BookMarkRes, error)
	GetIfBlogBookMarked(context.Context, *BookMarkReq) (*BookMarkRes, error)
	GetBookMarkCounts(context.Context, *BookMarkReq) (*CountResp, error)
	GetLikeCounts(context.Context, *BookMarkReq) (*CountResp, error)
	// Invite a co author
	InviteCoAuthor(context.Context, *CoAuthorAccessReq) (*CoAuthorAccessRes, error)
	// Accept co author invitation
	// Reject co author invitation
	// Revoke co author invitation access
	RevokeCoAuthorAccess(context.Context, *CoAuthorAccessReq) (*CoAuthorAccessRes, error)
	GetBlogsByUserIds(context.Context, *BlogsByUserIdsReq) (*BlogsByUserNameRes, error)
	CreateNewTopics(context.Context, *CreateTopicsReq) (*CreateTopicsRes, error)
	GetBatchUserDetails(context.Context, *GetBatchUserDetailsReq) (*GetBatchUserDetailsRes, error)
	// Business Cards (owned by account_id, stored in business_cards table)
	CreateBusinessCard(context.Context, *CreateBusinessCardReq) (*BusinessCard, error)
	GetBusinessCard(context.Context, *GetBusinessCardReq) (*BusinessCard, error)
	ListBusinessCards(context.Context, *ListBusinessCardsReq) (*ListBusinessCardsRes, error)
	UpdateBusinessCard(context.Context, *UpdateBusinessCardReq) (*BusinessCard, error)
	DeleteBusinessCard(context.Context, *DeleteBusinessCardReq) (*DeleteBusinessCardRes, error)
	// Private addresses (owned by account_id, stored in user_addresses table)
	CreateUserAddress(context.Context, *CreateUserAddressReq) (*UserAddress, error)
	GetUserAddress(context.Context, *GetUserAddressReq) (*UserAddress, error)
	ListUserAddresses(context.Context, *ListUserAddressesReq) (*ListUserAddressesRes, error)
	UpdateUserAddress(context.Context, *UpdateUserAddressReq) (*UserAddress, error)
	DeleteUserAddress(context.Context, *DeleteUserAddressReq) (*DeleteUserAddressRes, error)
	// Account verification (blue-check)
	SubmitVerificationRequest(context.Context, *SubmitVerificationReq) (*VerificationRequest, error)
	GetMyVerification(context.Context, *GetVerificationReq) (*VerificationRequest, error)
	CancelVerificationRequest(context.Context, *GetVerificationReq) (*VerificationActionRes, error)
	// Admin review surface
	ListVerificationRequests(context.Context, *ListVerificationReq) (*ListVerificationRes, error)
	ReviewVerificationRequest(context.Context, *ReviewVerificationReq) (*VerificationRequest, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetUserActivities(context.Context, *UserActivityReq) (*UserActivityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserActivities not implemented")
}
func (UnimplementedUserServiceServer) GetUserProfile(context.Context, *UserProfileReq) (*UserProfileRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserProfile(context.Context, *UpdateUserProfileReq) (*UpdateUserProfileRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserProfile not implemented")
}
func (UnimplementedUserServiceServer) DeleteUserAccount(context.Context, *DeleteUserProfileReq) (*DeleteUserProfileRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserAccount not implemented")
}
func (UnimplementedUserServiceServer) GetAllTopics(context.Context, *GetTopicsRequests) (*GetTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllTopics not implemented")
}
func (UnimplementedUserServiceServer) GetAllCategories(context.Context, *GetAllCategoriesReq) (*GetAllCategoriesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllCategories not implemented")
}
func (UnimplementedUserServiceServer) GetUserDetails(context.Context, *UserDetailReq) (*UserDetailsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDetails not implemented")
}
func (UnimplementedUserServiceServer) FollowTopics(context.Context, *TopicActionReq) (*TopicActionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowTopics not implemented")
}
func (UnimplementedUserServiceServer) UnFollowTopics(context.Context, *TopicActionReq) (*TopicActionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UnFollowTopics not implemented")
}
func (UnimplementedUserServiceServer) FollowUser(context.Context, *UserFollowReq) (*UserFollowRes, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowUser not implemented")
}
func (UnimplementedUserServiceServer) UnFollowUser(context.Context, *UserFollowReq) (*UserFollowRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UnFollowUser not implemented")
}
func (UnimplementedUserServiceServer) GetFollowers(context.Context, *UserDetailReq) (*FollowerFollowingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowers not implemented")
}
func (UnimplementedUserServiceServer) GetFollowing(context.Context, *UserDetailReq) (*FollowerFollowingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowing not implemented")
}
func (UnimplementedUserServiceServer) GetIfIFollowedUser(context.Context, *UserFollowReq) (*UserFollowRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIfIFollowedUser not implemented")
}
func (UnimplementedUserServiceServer) GetFollowersFollowingCounts(context.Context, *UserDetailReq) (*FollowerFollowingCountsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowersFollowingCounts not implemented")
}
func (UnimplementedUserServiceServer) SearchUser(grpc.BidiStreamingServer[UserDetailReq, FollowerFollowingResp]) error {
	return status.Error(codes.Unimplemented, "method SearchUser not implemented")
}
func (UnimplementedUserServiceServer) BookMarkBlog(context.Context, *BookMarkReq) (*BookMarkRes, error) {
	return nil, status.Error(codes.Unimplemented, "method BookMarkBlog not implemented")
}
func (UnimplementedUserServiceServer) GetBookMarks(context.Context, *BookMarkReq) (*BookMarkRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookMarks not implemented")
}
func (UnimplementedUserServiceServer) RemoveBookMark(context.Context, *BookMarkReq) (*BookMarkRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBookMark not implemented")
}
func (UnimplementedUserServiceServer) LikeBlog(context.Context, *BookMarkReq) (*BookMarkRes, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeBlog not implemented")
}
func (UnimplementedUserServiceServer) UnlikeBlog(context.Context, *BookMarkReq) (*BookMarkRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlikeBlog not implemented")
}
func (UnimplementedUserServiceServer) GetIfBlogLiked(context.Context, *BookMarkReq) (*BookMarkRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIfBlogLiked not implemented")
}
func (UnimplementedUserServiceServer) GetIfBlogBookMarked(context.Context, *BookMarkReq) (*BookMarkRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIfBlogBookMarked not implemented")
}
func (UnimplementedUserServiceServer) GetBookMarkCounts(context.Context, *BookMarkReq) (*CountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBookMarkCounts not implemented")
}
func (UnimplementedUserServiceServer) GetLikeCounts(context.Context, *BookMarkReq) (*CountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLikeCounts not implemented")
}
func (UnimplementedUserServiceServer) InviteCoAuthor(context.Context, *CoAuthorAccessReq) (*CoAuthorAccessRes, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteCoAuthor not implemented")
}
func (UnimplementedUserServiceServer) RevokeCoAuthorAccess(context.Context, *CoAuthorAccessReq) (*CoAuthorAccessRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCoAuthorAccess not implemented")
}
func (UnimplementedUserServiceServer) GetBlogsByUserIds(context.Context, *BlogsByUserIdsReq) (*BlogsByUserNameRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlogsByUserIds not implemented")
}
func (UnimplementedUserServiceServer) CreateNewTopics(context.Context, *CreateTopicsReq) (*CreateTopicsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewTopics not implemented")
}
func (UnimplementedUserServiceServer) GetBatchUserDetails(context.Context, *GetBatchUserDetailsReq) (*GetBatchUserDetailsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBatchUserDetails not implemented")
}
func (UnimplementedUserServiceServer) CreateBusinessCard(context.Context, *CreateBusinessCardReq) (*BusinessCard, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBusinessCard not implemented")
}
func (UnimplementedUserServiceServer) GetBusinessCard(context.Context, *GetBusinessCardReq) (*BusinessCard, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBusinessCard not implemented")
}
func (UnimplementedUserServiceServer) ListBusinessCards(context.Context, *ListBusinessCardsReq) (*ListBusinessCardsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBusinessCards not implemented")
}
func (UnimplementedUserServiceServer) UpdateBusinessCard(context.Context, *UpdateBusinessCardReq) (*BusinessCard, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBusinessCard not implemented")
}
func (UnimplementedUserServiceServer) DeleteBusinessCard(context.Context, *DeleteBusinessCardReq) (*DeleteBusinessCardRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBusinessCard not implemented")
}
func (UnimplementedUserServiceServer) CreateUserAddress(context.Context, *CreateUserAddressReq) (*UserAddress, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserAddress not implemented")
}
func (UnimplementedUserServiceServer) GetUserAddress(context.Context, *GetUserAddressReq) (*UserAddress, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAddress not implemented")
}
func (UnimplementedUserServiceServer) ListUserAddresses(context.Context, *ListUserAddressesReq) (*ListUserAddressesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserAddresses not implemented")
}
func (UnimplementedUserServiceServer) UpdateUserAddress(context.Context, *UpdateUserAddressReq) (*UserAddress, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserAddress not implemented")
}
func (UnimplementedUserServiceServer) DeleteUserAddress(context.Context, *DeleteUserAddressReq) (*DeleteUserAddressRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserAddress not implemented")
}
func (UnimplementedUserServiceServer) SubmitVerificationRequest(context.Context, *SubmitVerificationReq) (*VerificationRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitVerificationRequest not implemented")
}
func (UnimplementedUserServiceServer) GetMyVerification(context.Context, *GetVerificationReq) (*VerificationRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyVerification not implemented")
}
func (UnimplementedUserServiceServer) CancelVerificationRequest(context.Context, *GetVerificationReq) (*VerificationActionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelVerificationRequest not implemented")
}
func (UnimplementedUserServiceServer) ListVerificationRequests(context.Context, *ListVerificationReq) (*ListVerificationRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVerificationRequests not implemented")
}
func (UnimplementedUserServiceServer) ReviewVerificationRequest(context.Context, *ReviewVerificationReq) (*VerificationRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewVerificationRequest not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUserActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserActivities(ctx, req.(*UserActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserProfile(ctx, req.(*UserProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserProfile(ctx, req.(*UpdateUserProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteUserAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUserAccount(ctx, req.(*DeleteUserProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAllTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicsRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAllTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetAllTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAllTopics(ctx, req.(*GetTopicsRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAllCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCategoriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAllCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetAllCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAllCategories(ctx, req.(*GetAllCategoriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserDetails(ctx, req.(*UserDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FollowTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FollowTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_FollowTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FollowTopics(ctx, req.(*TopicActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UnFollowTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UnFollowTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UnFollowTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UnFollowTopics(ctx, req.(*TopicActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FollowUser(ctx, req.(*UserFollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UnFollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UnFollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UnFollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UnFollowUser(ctx, req.(*UserFollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFollowers(ctx, req.(*UserDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFollowing(ctx, req.(*UserDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetIfIFollowedUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetIfIFollowedUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetIfIFollowedUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetIfIFollowedUser(ctx, req.(*UserFollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFollowersFollowingCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFollowersFollowingCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetFollowersFollowingCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFollowersFollowingCounts(ctx, req.(*UserDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SearchUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).SearchUser(&grpc.GenericServerStream[UserDetailReq, FollowerFollowingResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_SearchUserServer = grpc.BidiStreamingServer[UserDetailReq, FollowerFollowingResp]

func _UserService_BookMarkBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).BookMarkBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_BookMarkBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).BookMarkBlog(ctx, req.(*BookMarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetBookMarks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetBookMarks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetBookMarks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetBookMarks(ctx, req.(*BookMarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveBookMark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveBookMark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RemoveBookMark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveBookMark(ctx, req.(*BookMarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LikeBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LikeBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LikeBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LikeBlog(ctx, req.(*BookMarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UnlikeBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UnlikeBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UnlikeBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UnlikeBlog(ctx, req.(*BookMarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetIfBlogLiked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetIfBlogLiked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetIfBlogLiked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetIfBlogLiked(ctx, req.(*BookMarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetIfBlogBookMarked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetIfBlogBookMarked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetIfBlogBookMarked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetIfBlogBookMarked(ctx, req.(*BookMarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetBookMarkCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetBookMarkCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetBookMarkCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetBookMarkCounts(ctx, req.(*BookMarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetLikeCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookMarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetLikeCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetLikeCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetLikeCounts(ctx, req.(*BookMarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_InviteCoAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoAuthorAccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).InviteCoAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_InviteCoAuthor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).InviteCoAuthor(ctx, req.(*CoAuthorAccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RevokeCoAuthorAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoAuthorAccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RevokeCoAuthorAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RevokeCoAuthorAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RevokeCoAuthorAccess(ctx, req.(*CoAuthorAccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetBlogsByUserIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogsByUserIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetBlogsByUserIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetBlogsByUserIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetBlogsByUserIds(ctx, req.(*BlogsByUserIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateNewTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateNewTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateNewTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateNewTopics(ctx, req.(*CreateTopicsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetBatchUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchUserDetailsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetBatchUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetBatchUserDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetBatchUserDetails(ctx, req.(*GetBatchUserDetailsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateBusinessCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBusinessCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateBusinessCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateBusinessCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateBusinessCard(ctx, req.(*CreateBusinessCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetBusinessCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetBusinessCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetBusinessCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetBusinessCard(ctx, req.(*GetBusinessCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListBusinessCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBusinessCardsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListBusinessCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListBusinessCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListBusinessCards(ctx, req.(*ListBusinessCardsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateBusinessCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBusinessCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateBusinessCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateBusinessCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateBusinessCard(ctx, req.(*UpdateBusinessCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteBusinessCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBusinessCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteBusinessCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteBusinessCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteBusinessCard(ctx, req.(*DeleteBusinessCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUserAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUserAddress(ctx, req.(*CreateUserAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserAddress(ctx, req.(*GetUserAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUserAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserAddressesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUserAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListUserAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUserAddresses(ctx, req.(*ListUserAddressesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateUserAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserAddress(ctx, req.(*UpdateUserAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUserAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUserAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteUserAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUserAddress(ctx, req.(*DeleteUserAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SubmitVerificationRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitVerificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SubmitVerificationRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SubmitVerificationRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SubmitVerificationRequest(ctx, req.(*SubmitVerificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetMyVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetMyVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetMyVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetMyVerification(ctx, req.(*GetVerificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CancelVerificationRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CancelVerificationRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CancelVerificationRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CancelVerificationRequest(ctx, req.(*GetVerificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListVerificationRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVerificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListVerificationRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListVerificationRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListVerificationRequests(ctx, req.(*ListVerificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReviewVerificationRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewVerificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReviewVerificationRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ReviewVerificationRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReviewVerificationRequest(ctx, req.(*ReviewVerificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_svc.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserActivities",
			Handler:    _UserService_GetUserActivities_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _UserService_GetUserProfile_Handler,
		},
		{
			MethodName: "UpdateUserProfile",
			Handler:    _UserService_UpdateUserProfile_Handler,
		},
		{
			MethodName: "DeleteUserAccount",
			Handler:    _UserService_DeleteUserAccount_Handler,
		},
		{
			MethodName: "GetAllTopics",
			Handler:    _UserService_GetAllTopics_Handler,
		},
		{
			MethodName: "GetAllCategories",
			Handler:    _UserService_GetAllCategories_Handler,
		},
		{
			MethodName: "GetUserDetails",
			Handler:    _UserService_GetUserDetails_Handler,
		},
		{
			MethodName: "FollowTopics",
			Handler:    _UserService_FollowTopics_Handler,
		},
		{
			MethodName: "UnFollowTopics",
			Handler:    _UserService_UnFollowTopics_Handler,
		},
		{
			MethodName: "FollowUser",
			Handler:    _UserService_FollowUser_Handler,
		},
		{
			MethodName: "UnFollowUser",
			Handler:    _UserService_UnFollowUser_Handler,
		},
		{
			MethodName: "GetFollowers",
			Handler:    _UserService_GetFollowers_Handler,
		},
		{
			MethodName: "GetFollowing",
			Handler:    _UserService_GetFollowing_Handler,
		},
		{
			MethodName: "GetIfIFollowedUser",
			Handler:    _UserService_GetIfIFollowedUser_Handler,
		},
		{
			MethodName: "GetFollowersFollowingCounts",
			Handler:    _UserService_GetFollowersFollowingCounts_Handler,
		},
		{
			MethodName: "BookMarkBlog",
			Handler:    _UserService_BookMarkBlog_Handler,
		},
		{
			MethodName: "GetBookMarks",
			Handler:    _UserService_GetBookMarks_Handler,
		},
		{
			MethodName: "RemoveBookMark",
			Handler:    _UserService_RemoveBookMark_Handler,
		},
		{
			MethodName: "LikeBlog",
			Handler:    _UserService_LikeBlog_Handler,
		},
		{
			MethodName: "UnlikeBlog",
			Handler:    _UserService_UnlikeBlog_Handler,
		},
		{
			MethodName: "GetIfBlogLiked",
			Handler:    _UserService_GetIfBlogLiked_Handler,
		},
		{
			MethodName: "GetIfBlogBookMarked",
			Handler:    _UserService_GetIfBlogBookMarked_Handler,
		},
		{
			MethodName: "GetBookMarkCounts",
			Handler:    _UserService_GetBookMarkCounts_Handler,
		},
		{
			MethodName: "GetLikeCounts",
			Handler:    _UserService_GetLikeCounts_Handler,
		},
		{
			MethodName: "InviteCoAuthor",
			Handler:    _UserService_InviteCoAuthor_Handler,
		},
		{
			MethodName: "RevokeCoAuthorAccess",
			Handler:    _UserService_RevokeCoAuthorAccess_Handler,
		},
		{
			MethodName: "GetBlogsByUserIds",
			Handler:    _UserService_GetBlogsByUserIds_Handler,
		},
		{
			MethodName: "CreateNewTopics",
			Handler:    _UserService_CreateNewTopics_Handler,
		},
		{
			MethodName: "GetBatchUserDetails",
			Handler:    _UserService_GetBatchUserDetails_Handler,
		},
		{
			MethodName: "CreateBusinessCard",
			Handler:    _UserService_CreateBusinessCard_Handler,
		},
		{
			MethodName: "GetBusinessCard",
			Handler:    _UserService_GetBusinessCard_Handler,
		},
		{
			MethodName: "ListBusinessCards",
			Handler:    _UserService_ListBusinessCards_Handler,
		},
		{
			MethodName: "UpdateBusinessCard",
			Handler:    _UserService_UpdateBusinessCard_Handler,
		},
		{
			MethodName: "DeleteBusinessCard",
			Handler:    _UserService_DeleteBusinessCard_Handler,
		},
		{
			MethodName: "CreateUserAddress",
			Handler:    _UserService_CreateUserAddress_Handler,
		},
		{
			MethodName: "GetUserAddress",
			Handler:    _UserService_GetUserAddress_Handler,
		},
		{
			MethodName: "ListUserAddresses",
			Handler:    _UserService_ListUserAddresses_Handler,
		},
		{
			MethodName: "UpdateUserAddress",
			Handler:    _UserService_UpdateUserAddress_Handler,
		},
		{
			MethodName: "DeleteUserAddress",
			Handler:    _UserService_DeleteUserAddress_Handler,
		},
		{
			MethodName: "SubmitVerificationRequest",
			Handler:    _UserService_SubmitVerificationRequest_Handler,
		},
		{
			MethodName: "GetMyVerification",
			Handler:    _UserService_GetMyVerification_Handler,
		},
		{
			MethodName: "CancelVerificationRequest",
			Handler:    _UserService_CancelVerificationRequest_Handler,
		},
		{
			MethodName: "ListVerificationRequests",
			Handler:    _UserService_ListVerificationRequests_Handler,
		},
		{
			MethodName: "ReviewVerificationRequest",
			Handler:    _UserService_ReviewVerificationRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchUser",
			Handler:       _UserService_SearchUser_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "apis/serviceconn/gateway_user/pb/gw_user.proto",
}
