// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: apis/serviceconn/gateway_social_post/pb/gw_social_post.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SocialPostService_CreatePost_FullMethodName             = "/social_post_svc.SocialPostService/CreatePost"
	SocialPostService_GetPost_FullMethodName                = "/social_post_svc.SocialPostService/GetPost"
	SocialPostService_UpdatePost_FullMethodName             = "/social_post_svc.SocialPostService/UpdatePost"
	SocialPostService_DeleteDraft_FullMethodName            = "/social_post_svc.SocialPostService/DeleteDraft"
	SocialPostService_ListPosts_FullMethodName              = "/social_post_svc.SocialPostService/ListPosts"
	SocialPostService_UpsertRendition_FullMethodName        = "/social_post_svc.SocialPostService/UpsertRendition"
	SocialPostService_SetRenditionMedia_FullMethodName      = "/social_post_svc.SocialPostService/SetRenditionMedia"
	SocialPostService_SchedulePost_FullMethodName           = "/social_post_svc.SocialPostService/SchedulePost"
	SocialPostService_CancelSchedule_FullMethodName         = "/social_post_svc.SocialPostService/CancelSchedule"
	SocialPostService_ReschedulePost_FullMethodName         = "/social_post_svc.SocialPostService/ReschedulePost"
	SocialPostService_PublishNow_FullMethodName             = "/social_post_svc.SocialPostService/PublishNow"
	SocialPostService_ListCalendar_FullMethodName           = "/social_post_svc.SocialPostService/ListCalendar"
	SocialPostService_ListQueue_FullMethodName              = "/social_post_svc.SocialPostService/ListQueue"
	SocialPostService_GetJobStatus_FullMethodName           = "/social_post_svc.SocialPostService/GetJobStatus"
	SocialPostService_ReplayJob_FullMethodName              = "/social_post_svc.SocialPostService/ReplayJob"
	SocialPostService_ListAccounts_FullMethodName           = "/social_post_svc.SocialPostService/ListAccounts"
	SocialPostService_LinkAccount_FullMethodName            = "/social_post_svc.SocialPostService/LinkAccount"
	SocialPostService_DisconnectAccount_FullMethodName      = "/social_post_svc.SocialPostService/DisconnectAccount"
	SocialPostService_ListValidationMetadata_FullMethodName = "/social_post_svc.SocialPostService/ListValidationMetadata"
	SocialPostService_ImportStudioAsset_FullMethodName      = "/social_post_svc.SocialPostService/ImportStudioAsset"
	SocialPostService_ListMediaAssets_FullMethodName        = "/social_post_svc.SocialPostService/ListMediaAssets"
	SocialPostService_DeleteMediaAsset_FullMethodName       = "/social_post_svc.SocialPostService/DeleteMediaAsset"
	SocialPostService_ReorderQueue_FullMethodName           = "/social_post_svc.SocialPostService/ReorderQueue"
	SocialPostService_ListPostHistory_FullMethodName        = "/social_post_svc.SocialPostService/ListPostHistory"
)

// SocialPostServiceClient is the client API for SocialPostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SocialPostServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	DeleteDraft(ctx context.Context, in *DeleteDraftRequest, opts ...grpc.CallOption) (*PostResponse, error)
	ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
	UpsertRendition(ctx context.Context, in *UpsertRenditionRequest, opts ...grpc.CallOption) (*PostResponse, error)
	SetRenditionMedia(ctx context.Context, in *SetRenditionMediaRequest, opts ...grpc.CallOption) (*PostResponse, error)
	SchedulePost(ctx context.Context, in *SchedulePostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	CancelSchedule(ctx context.Context, in *PostActionRequest, opts ...grpc.CallOption) (*PostResponse, error)
	ReschedulePost(ctx context.Context, in *SchedulePostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	PublishNow(ctx context.Context, in *PostActionRequest, opts ...grpc.CallOption) (*PostResponse, error)
	ListCalendar(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
	ListQueue(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
	GetJobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatus, error)
	ReplayJob(ctx context.Context, in *ReplayJobRequest, opts ...grpc.CallOption) (*JobStatus, error)
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	LinkAccount(ctx context.Context, in *LinkAccountRequest, opts ...grpc.CallOption) (*SocialAccount, error)
	DisconnectAccount(ctx context.Context, in *DisconnectAccountRequest, opts ...grpc.CallOption) (*DisconnectAccountResponse, error)
	ListValidationMetadata(ctx context.Context, in *ListValidationMetadataRequest, opts ...grpc.CallOption) (*ListValidationMetadataResponse, error)
	ImportStudioAsset(ctx context.Context, in *ImportStudioAssetRequest, opts ...grpc.CallOption) (*ImportStudioAssetResponse, error)
	ListMediaAssets(ctx context.Context, in *ListMediaAssetsRequest, opts ...grpc.CallOption) (*ListMediaAssetsResponse, error)
	DeleteMediaAsset(ctx context.Context, in *DeleteMediaAssetRequest, opts ...grpc.CallOption) (*DeleteMediaAssetResponse, error)
	ReorderQueue(ctx context.Context, in *ReorderQueueRequest, opts ...grpc.CallOption) (*ReorderQueueResponse, error)
	ListPostHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
}

type socialPostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialPostServiceClient(cc grpc.ClientConnInterface) SocialPostServiceClient {
	return &socialPostServiceClient{cc}
}

func (c *socialPostServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, SocialPostService_CreatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, SocialPostService_GetPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, SocialPostService_UpdatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) DeleteDraft(ctx context.Context, in *DeleteDraftRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, SocialPostService_DeleteDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, SocialPostService_ListPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) UpsertRendition(ctx context.Context, in *UpsertRenditionRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, SocialPostService_UpsertRendition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) SetRenditionMedia(ctx context.Context, in *SetRenditionMediaRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, SocialPostService_SetRenditionMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) SchedulePost(ctx context.Context, in *SchedulePostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, SocialPostService_SchedulePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) CancelSchedule(ctx context.Context, in *PostActionRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, SocialPostService_CancelSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) ReschedulePost(ctx context.Context, in *SchedulePostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, SocialPostService_ReschedulePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) PublishNow(ctx context.Context, in *PostActionRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, SocialPostService_PublishNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) ListCalendar(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, SocialPostService_ListCalendar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) ListQueue(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, SocialPostService_ListQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) GetJobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, SocialPostService_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) ReplayJob(ctx context.Context, in *ReplayJobRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, SocialPostService_ReplayJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, SocialPostService_ListAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) LinkAccount(ctx context.Context, in *LinkAccountRequest, opts ...grpc.CallOption) (*SocialAccount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SocialAccount)
	err := c.cc.Invoke(ctx, SocialPostService_LinkAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) DisconnectAccount(ctx context.Context, in *DisconnectAccountRequest, opts ...grpc.CallOption) (*DisconnectAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectAccountResponse)
	err := c.cc.Invoke(ctx, SocialPostService_DisconnectAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) ListValidationMetadata(ctx context.Context, in *ListValidationMetadataRequest, opts ...grpc.CallOption) (*ListValidationMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListValidationMetadataResponse)
	err := c.cc.Invoke(ctx, SocialPostService_ListValidationMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) ImportStudioAsset(ctx context.Context, in *ImportStudioAssetRequest, opts ...grpc.CallOption) (*ImportStudioAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportStudioAssetResponse)
	err := c.cc.Invoke(ctx, SocialPostService_ImportStudioAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) ListMediaAssets(ctx context.Context, in *ListMediaAssetsRequest, opts ...grpc.CallOption) (*ListMediaAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMediaAssetsResponse)
	err := c.cc.Invoke(ctx, SocialPostService_ListMediaAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) DeleteMediaAsset(ctx context.Context, in *DeleteMediaAssetRequest, opts ...grpc.CallOption) (*DeleteMediaAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMediaAssetResponse)
	err := c.cc.Invoke(ctx, SocialPostService_DeleteMediaAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) ReorderQueue(ctx context.Context, in *ReorderQueueRequest, opts ...grpc.CallOption) (*ReorderQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReorderQueueResponse)
	err := c.cc.Invoke(ctx, SocialPostService_ReorderQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialPostServiceClient) ListPostHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, SocialPostService_ListPostHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialPostServiceServer is the server API for SocialPostService service.
// All implementations must embed UnimplementedSocialPostServiceServer
// for forward compatibility.
type SocialPostServiceServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*PostResponse, error)
	GetPost(context.Context, *GetPostRequest) (*PostResponse, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*PostResponse, error)
	DeleteDraft(context.Context, *DeleteDraftRequest) (*PostResponse, error)
	ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error)
	UpsertRendition(context.Context, *UpsertRenditionRequest) (*PostResponse, error)
	SetRenditionMedia(context.Context, *SetRenditionMediaRequest) (*PostResponse, error)
	SchedulePost(context.Context, *SchedulePostRequest) (*PostResponse, error)
	CancelSchedule(context.Context, *PostActionRequest) (*PostResponse, error)
	ReschedulePost(context.Context, *SchedulePostRequest) (*PostResponse, error)
	PublishNow(context.Context, *PostActionRequest) (*PostResponse, error)
	ListCalendar(context.Context, *ListPostsRequest) (*ListPostsResponse, error)
	ListQueue(context.Context, *ListPostsRequest) (*ListPostsResponse, error)
	GetJobStatus(context.Context, *JobStatusRequest) (*JobStatus, error)
	ReplayJob(context.Context, *ReplayJobRequest) (*JobStatus, error)
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	LinkAccount(context.Context, *LinkAccountRequest) (*SocialAccount, error)
	DisconnectAccount(context.Context, *DisconnectAccountRequest) (*DisconnectAccountResponse, error)
	ListValidationMetadata(context.Context, *ListValidationMetadataRequest) (*ListValidationMetadataResponse, error)
	ImportStudioAsset(context.Context, *ImportStudioAssetRequest) (*ImportStudioAssetResponse, error)
	ListMediaAssets(context.Context, *ListMediaAssetsRequest) (*ListMediaAssetsResponse, error)
	DeleteMediaAsset(context.Context, *DeleteMediaAssetRequest) (*DeleteMediaAssetResponse, error)
	ReorderQueue(context.Context, *ReorderQueueRequest) (*ReorderQueueResponse, error)
	ListPostHistory(context.Context, *HistoryRequest) (*HistoryResponse, error)
	mustEmbedUnimplementedSocialPostServiceServer()
}

// UnimplementedSocialPostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialPostServiceServer struct{}

func (UnimplementedSocialPostServiceServer) CreatePost(context.Context, *CreatePostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedSocialPostServiceServer) GetPost(context.Context, *GetPostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (UnimplementedSocialPostServiceServer) UpdatePost(context.Context, *UpdatePostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (UnimplementedSocialPostServiceServer) DeleteDraft(context.Context, *DeleteDraftRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDraft not implemented")
}
func (UnimplementedSocialPostServiceServer) ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPosts not implemented")
}
func (UnimplementedSocialPostServiceServer) UpsertRendition(context.Context, *UpsertRenditionRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertRendition not implemented")
}
func (UnimplementedSocialPostServiceServer) SetRenditionMedia(context.Context, *SetRenditionMediaRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRenditionMedia not implemented")
}
func (UnimplementedSocialPostServiceServer) SchedulePost(context.Context, *SchedulePostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SchedulePost not implemented")
}
func (UnimplementedSocialPostServiceServer) CancelSchedule(context.Context, *PostActionRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelSchedule not implemented")
}
func (UnimplementedSocialPostServiceServer) ReschedulePost(context.Context, *SchedulePostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReschedulePost not implemented")
}
func (UnimplementedSocialPostServiceServer) PublishNow(context.Context, *PostActionRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishNow not implemented")
}
func (UnimplementedSocialPostServiceServer) ListCalendar(context.Context, *ListPostsRequest) (*ListPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCalendar not implemented")
}
func (UnimplementedSocialPostServiceServer) ListQueue(context.Context, *ListPostsRequest) (*ListPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQueue not implemented")
}
func (UnimplementedSocialPostServiceServer) GetJobStatus(context.Context, *JobStatusRequest) (*JobStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedSocialPostServiceServer) ReplayJob(context.Context, *ReplayJobRequest) (*JobStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplayJob not implemented")
}
func (UnimplementedSocialPostServiceServer) ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
}
func (UnimplementedSocialPostServiceServer) LinkAccount(context.Context, *LinkAccountRequest) (*SocialAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkAccount not implemented")
}
func (UnimplementedSocialPostServiceServer) DisconnectAccount(context.Context, *DisconnectAccountRequest) (*DisconnectAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectAccount not implemented")
}
func (UnimplementedSocialPostServiceServer) ListValidationMetadata(context.Context, *ListValidationMetadataRequest) (*ListValidationMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListValidationMetadata not implemented")
}
func (UnimplementedSocialPostServiceServer) ImportStudioAsset(context.Context, *ImportStudioAssetRequest) (*ImportStudioAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportStudioAsset not implemented")
}
func (UnimplementedSocialPostServiceServer) ListMediaAssets(context.Context, *ListMediaAssetsRequest) (*ListMediaAssetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMediaAssets not implemented")
}
func (UnimplementedSocialPostServiceServer) DeleteMediaAsset(context.Context, *DeleteMediaAssetRequest) (*DeleteMediaAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMediaAsset not implemented")
}
func (UnimplementedSocialPostServiceServer) ReorderQueue(context.Context, *ReorderQueueRequest) (*ReorderQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReorderQueue not implemented")
}
func (UnimplementedSocialPostServiceServer) ListPostHistory(context.Context, *HistoryRequest) (*HistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPostHistory not implemented")
}
func (UnimplementedSocialPostServiceServer) mustEmbedUnimplementedSocialPostServiceServer() {}
func (UnimplementedSocialPostServiceServer) testEmbeddedByValue()                           {}

// UnsafeSocialPostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialPostServiceServer will
// result in compilation errors.
type UnsafeSocialPostServiceServer interface {
	mustEmbedUnimplementedSocialPostServiceServer()
}

func RegisterSocialPostServiceServer(s grpc.ServiceRegistrar, srv SocialPostServiceServer) {
	// If the following call pancis, it indicates UnimplementedSocialPostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocialPostService_ServiceDesc, srv)
}

func _SocialPostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_GetPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_UpdatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_DeleteDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).DeleteDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_DeleteDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).DeleteDraft(ctx, req.(*DeleteDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_ListPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).ListPosts(ctx, req.(*ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_UpsertRendition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRenditionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).UpsertRendition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_UpsertRendition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).UpsertRendition(ctx, req.(*UpsertRenditionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_SetRenditionMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRenditionMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).SetRenditionMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_SetRenditionMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).SetRenditionMedia(ctx, req.(*SetRenditionMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_SchedulePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).SchedulePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_SchedulePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).SchedulePost(ctx, req.(*SchedulePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_CancelSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).CancelSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_CancelSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).CancelSchedule(ctx, req.(*PostActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_ReschedulePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).ReschedulePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_ReschedulePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).ReschedulePost(ctx, req.(*SchedulePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_PublishNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).PublishNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_PublishNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).PublishNow(ctx, req.(*PostActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_ListCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).ListCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_ListCalendar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).ListCalendar(ctx, req.(*ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_ListQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).ListQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_ListQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).ListQueue(ctx, req.(*ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).GetJobStatus(ctx, req.(*JobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_ReplayJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).ReplayJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_ReplayJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).ReplayJob(ctx, req.(*ReplayJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_ListAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_LinkAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).LinkAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_LinkAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).LinkAccount(ctx, req.(*LinkAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_DisconnectAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).DisconnectAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_DisconnectAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).DisconnectAccount(ctx, req.(*DisconnectAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_ListValidationMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListValidationMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).ListValidationMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_ListValidationMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).ListValidationMetadata(ctx, req.(*ListValidationMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_ImportStudioAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportStudioAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).ImportStudioAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_ImportStudioAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).ImportStudioAsset(ctx, req.(*ImportStudioAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_ListMediaAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMediaAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).ListMediaAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_ListMediaAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).ListMediaAssets(ctx, req.(*ListMediaAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_DeleteMediaAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMediaAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).DeleteMediaAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_DeleteMediaAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).DeleteMediaAsset(ctx, req.(*DeleteMediaAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_ReorderQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).ReorderQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_ReorderQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).ReorderQueue(ctx, req.(*ReorderQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialPostService_ListPostHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialPostServiceServer).ListPostHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialPostService_ListPostHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialPostServiceServer).ListPostHistory(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SocialPostService_ServiceDesc is the grpc.ServiceDesc for SocialPostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialPostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social_post_svc.SocialPostService",
	HandlerType: (*SocialPostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _SocialPostService_CreatePost_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _SocialPostService_GetPost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _SocialPostService_UpdatePost_Handler,
		},
		{
			MethodName: "DeleteDraft",
			Handler:    _SocialPostService_DeleteDraft_Handler,
		},
		{
			MethodName: "ListPosts",
			Handler:    _SocialPostService_ListPosts_Handler,
		},
		{
			MethodName: "UpsertRendition",
			Handler:    _SocialPostService_UpsertRendition_Handler,
		},
		{
			MethodName: "SetRenditionMedia",
			Handler:    _SocialPostService_SetRenditionMedia_Handler,
		},
		{
			MethodName: "SchedulePost",
			Handler:    _SocialPostService_SchedulePost_Handler,
		},
		{
			MethodName: "CancelSchedule",
			Handler:    _SocialPostService_CancelSchedule_Handler,
		},
		{
			MethodName: "ReschedulePost",
			Handler:    _SocialPostService_ReschedulePost_Handler,
		},
		{
			MethodName: "PublishNow",
			Handler:    _SocialPostService_PublishNow_Handler,
		},
		{
			MethodName: "ListCalendar",
			Handler:    _SocialPostService_ListCalendar_Handler,
		},
		{
			MethodName: "ListQueue",
			Handler:    _SocialPostService_ListQueue_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _SocialPostService_GetJobStatus_Handler,
		},
		{
			MethodName: "ReplayJob",
			Handler:    _SocialPostService_ReplayJob_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _SocialPostService_ListAccounts_Handler,
		},
		{
			MethodName: "LinkAccount",
			Handler:    _SocialPostService_LinkAccount_Handler,
		},
		{
			MethodName: "DisconnectAccount",
			Handler:    _SocialPostService_DisconnectAccount_Handler,
		},
		{
			MethodName: "ListValidationMetadata",
			Handler:    _SocialPostService_ListValidationMetadata_Handler,
		},
		{
			MethodName: "ImportStudioAsset",
			Handler:    _SocialPostService_ImportStudioAsset_Handler,
		},
		{
			MethodName: "ListMediaAssets",
			Handler:    _SocialPostService_ListMediaAssets_Handler,
		},
		{
			MethodName: "DeleteMediaAsset",
			Handler:    _SocialPostService_DeleteMediaAsset_Handler,
		},
		{
			MethodName: "ReorderQueue",
			Handler:    _SocialPostService_ReorderQueue_Handler,
		},
		{
			MethodName: "ListPostHistory",
			Handler:    _SocialPostService_ListPostHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis/serviceconn/gateway_social_post/pb/gw_social_post.proto",
}
