// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: apis/serviceconn/gateway_group/pb/gw_group.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GroupService_CreateGroup_FullMethodName        = "/group_svc.GroupService/CreateGroup"
	GroupService_UpdateGroup_FullMethodName        = "/group_svc.GroupService/UpdateGroup"
	GroupService_DeleteGroup_FullMethodName        = "/group_svc.GroupService/DeleteGroup"
	GroupService_PublishGroup_FullMethodName       = "/group_svc.GroupService/PublishGroup"
	GroupService_GetGroup_FullMethodName           = "/group_svc.GroupService/GetGroup"
	GroupService_ListGroups_FullMethodName         = "/group_svc.GroupService/ListGroups"
	GroupService_GetUserGroups_FullMethodName      = "/group_svc.GroupService/GetUserGroups"
	GroupService_JoinGroup_FullMethodName          = "/group_svc.GroupService/JoinGroup"
	GroupService_LeaveGroup_FullMethodName         = "/group_svc.GroupService/LeaveGroup"
	GroupService_ListMembers_FullMethodName        = "/group_svc.GroupService/ListMembers"
	GroupService_UpdateMemberRole_FullMethodName   = "/group_svc.GroupService/UpdateMemberRole"
	GroupService_RemoveMember_FullMethodName       = "/group_svc.GroupService/RemoveMember"
	GroupService_BanMember_FullMethodName          = "/group_svc.GroupService/BanMember"
	GroupService_ApproveJoinRequest_FullMethodName = "/group_svc.GroupService/ApproveJoinRequest"
	GroupService_RejectJoinRequest_FullMethodName  = "/group_svc.GroupService/RejectJoinRequest"
	GroupService_AddMember_FullMethodName          = "/group_svc.GroupService/AddMember"
	GroupService_CreateInvite_FullMethodName       = "/group_svc.GroupService/CreateInvite"
	GroupService_ListInvites_FullMethodName        = "/group_svc.GroupService/ListInvites"
	GroupService_RevokeInvite_FullMethodName       = "/group_svc.GroupService/RevokeInvite"
	GroupService_GetInvite_FullMethodName          = "/group_svc.GroupService/GetInvite"
	GroupService_AcceptInvite_FullMethodName       = "/group_svc.GroupService/AcceptInvite"
	GroupService_AddGroupRule_FullMethodName       = "/group_svc.GroupService/AddGroupRule"
	GroupService_UpdateGroupRule_FullMethodName    = "/group_svc.GroupService/UpdateGroupRule"
	GroupService_DeleteGroupRule_FullMethodName    = "/group_svc.GroupService/DeleteGroupRule"
	GroupService_Authorize_FullMethodName          = "/group_svc.GroupService/Authorize"
)

// GroupServiceClient is the client API for GroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupServiceClient interface {
	// Group CRUD
	CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*GroupResp, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*GroupResp, error)
	DeleteGroup(ctx context.Context, in *GroupActionReq, opts ...grpc.CallOption) (*BasicResp, error)
	PublishGroup(ctx context.Context, in *GroupActionReq, opts ...grpc.CallOption) (*GroupResp, error)
	GetGroup(ctx context.Context, in *GetGroupReq, opts ...grpc.CallOption) (*GroupResp, error)
	ListGroups(ctx context.Context, in *ListGroupsReq, opts ...grpc.CallOption) (*ListGroupsResp, error)
	GetUserGroups(ctx context.Context, in *ListGroupsReq, opts ...grpc.CallOption) (*ListGroupsResp, error)
	// Membership
	JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (*BasicResp, error)
	LeaveGroup(ctx context.Context, in *GroupActionReq, opts ...grpc.CallOption) (*BasicResp, error)
	ListMembers(ctx context.Context, in *ListGroupMembersReq, opts ...grpc.CallOption) (*ListGroupMembersResp, error)
	UpdateMemberRole(ctx context.Context, in *UpdateMemberRoleReq, opts ...grpc.CallOption) (*BasicResp, error)
	RemoveMember(ctx context.Context, in *UpdateMemberRoleReq, opts ...grpc.CallOption) (*BasicResp, error)
	BanMember(ctx context.Context, in *UpdateMemberRoleReq, opts ...grpc.CallOption) (*BasicResp, error)
	ApproveJoinRequest(ctx context.Context, in *JoinDecisionReq, opts ...grpc.CallOption) (*BasicResp, error)
	RejectJoinRequest(ctx context.Context, in *JoinDecisionReq, opts ...grpc.CallOption) (*BasicResp, error)
	// Direct add + invite links
	AddMember(ctx context.Context, in *AddMemberReq, opts ...grpc.CallOption) (*BasicResp, error)
	CreateInvite(ctx context.Context, in *CreateInviteReq, opts ...grpc.CallOption) (*InviteResp, error)
	ListInvites(ctx context.Context, in *ListInvitesReq, opts ...grpc.CallOption) (*ListInvitesResp, error)
	RevokeInvite(ctx context.Context, in *RevokeInviteReq, opts ...grpc.CallOption) (*BasicResp, error)
	GetInvite(ctx context.Context, in *GetInviteReq, opts ...grpc.CallOption) (*InviteResp, error)
	AcceptInvite(ctx context.Context, in *AcceptInviteReq, opts ...grpc.CallOption) (*BasicResp, error)
	// Rules
	AddGroupRule(ctx context.Context, in *GroupRuleReq, opts ...grpc.CallOption) (*GroupRuleResp, error)
	UpdateGroupRule(ctx context.Context, in *GroupRuleReq, opts ...grpc.CallOption) (*GroupRuleResp, error)
	DeleteGroupRule(ctx context.Context, in *GroupRuleActionReq, opts ...grpc.CallOption) (*BasicResp, error)
	// Authorization
	Authorize(ctx context.Context, in *AuthorizeGroupReq, opts ...grpc.CallOption) (*AuthorizeGroupResp, error)
}

type groupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupServiceClient(cc grpc.ClientConnInterface) GroupServiceClient {
	return &groupServiceClient{cc}
}

func (c *groupServiceClient) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*GroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResp)
	err := c.cc.Invoke(ctx, GroupService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*GroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResp)
	err := c.cc.Invoke(ctx, GroupService_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) DeleteGroup(ctx context.Context, in *GroupActionReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, GroupService_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) PublishGroup(ctx context.Context, in *GroupActionReq, opts ...grpc.CallOption) (*GroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResp)
	err := c.cc.Invoke(ctx, GroupService_PublishGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetGroup(ctx context.Context, in *GetGroupReq, opts ...grpc.CallOption) (*GroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResp)
	err := c.cc.Invoke(ctx, GroupService_GetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ListGroups(ctx context.Context, in *ListGroupsReq, opts ...grpc.CallOption) (*ListGroupsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResp)
	err := c.cc.Invoke(ctx, GroupService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetUserGroups(ctx context.Context, in *ListGroupsReq, opts ...grpc.CallOption) (*ListGroupsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResp)
	err := c.cc.Invoke(ctx, GroupService_GetUserGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, GroupService_JoinGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) LeaveGroup(ctx context.Context, in *GroupActionReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, GroupService_LeaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ListMembers(ctx context.Context, in *ListGroupMembersReq, opts ...grpc.CallOption) (*ListGroupMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupMembersResp)
	err := c.cc.Invoke(ctx, GroupService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) UpdateMemberRole(ctx context.Context, in *UpdateMemberRoleReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, GroupService_UpdateMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) RemoveMember(ctx context.Context, in *UpdateMemberRoleReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, GroupService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) BanMember(ctx context.Context, in *UpdateMemberRoleReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, GroupService_BanMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ApproveJoinRequest(ctx context.Context, in *JoinDecisionReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, GroupService_ApproveJoinRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) RejectJoinRequest(ctx context.Context, in *JoinDecisionReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, GroupService_RejectJoinRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) AddMember(ctx context.Context, in *AddMemberReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, GroupService_AddMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) CreateInvite(ctx context.Context, in *CreateInviteReq, opts ...grpc.CallOption) (*InviteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteResp)
	err := c.cc.Invoke(ctx, GroupService_CreateInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ListInvites(ctx context.Context, in *ListInvitesReq, opts ...grpc.CallOption) (*ListInvitesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInvitesResp)
	err := c.cc.Invoke(ctx, GroupService_ListInvites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) RevokeInvite(ctx context.Context, in *RevokeInviteReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, GroupService_RevokeInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetInvite(ctx context.Context, in *GetInviteReq, opts ...grpc.CallOption) (*InviteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteResp)
	err := c.cc.Invoke(ctx, GroupService_GetInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) AcceptInvite(ctx context.Context, in *AcceptInviteReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, GroupService_AcceptInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) AddGroupRule(ctx context.Context, in *GroupRuleReq, opts ...grpc.CallOption) (*GroupRuleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupRuleResp)
	err := c.cc.Invoke(ctx, GroupService_AddGroupRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) UpdateGroupRule(ctx context.Context, in *GroupRuleReq, opts ...grpc.CallOption) (*GroupRuleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupRuleResp)
	err := c.cc.Invoke(ctx, GroupService_UpdateGroupRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) DeleteGroupRule(ctx context.Context, in *GroupRuleActionReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, GroupService_DeleteGroupRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) Authorize(ctx context.Context, in *AuthorizeGroupReq, opts ...grpc.CallOption) (*AuthorizeGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeGroupResp)
	err := c.cc.Invoke(ctx, GroupService_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupServiceServer is the server API for GroupService service.
// All implementations must embed UnimplementedGroupServiceServer
// for forward compatibility.
type GroupServiceServer interface {
	// Group CRUD
	CreateGroup(context.Context, *CreateGroupReq) (*GroupResp, error)
	UpdateGroup(context.Context, *UpdateGroupReq) (*GroupResp, error)
	DeleteGroup(context.Context, *GroupActionReq) (*BasicResp, error)
	PublishGroup(context.Context, *GroupActionReq) (*GroupResp, error)
	GetGroup(context.Context, *GetGroupReq) (*GroupResp, error)
	ListGroups(context.Context, *ListGroupsReq) (*ListGroupsResp, error)
	GetUserGroups(context.Context, *ListGroupsReq) (*ListGroupsResp, error)
	// Membership
	JoinGroup(context.Context, *JoinGroupReq) (*BasicResp, error)
	LeaveGroup(context.Context, *GroupActionReq) (*BasicResp, error)
	ListMembers(context.Context, *ListGroupMembersReq) (*ListGroupMembersResp, error)
	UpdateMemberRole(context.Context, *UpdateMemberRoleReq) (*BasicResp, error)
	RemoveMember(context.Context, *UpdateMemberRoleReq) (*BasicResp, error)
	BanMember(context.Context, *UpdateMemberRoleReq) (*BasicResp, error)
	ApproveJoinRequest(context.Context, *JoinDecisionReq) (*BasicResp, error)
	RejectJoinRequest(context.Context, *JoinDecisionReq) (*BasicResp, error)
	// Direct add + invite links
	AddMember(context.Context, *AddMemberReq) (*BasicResp, error)
	CreateInvite(context.Context, *CreateInviteReq) (*InviteResp, error)
	ListInvites(context.Context, *ListInvitesReq) (*ListInvitesResp, error)
	RevokeInvite(context.Context, *RevokeInviteReq) (*BasicResp, error)
	GetInvite(context.Context, *GetInviteReq) (*InviteResp, error)
	AcceptInvite(context.Context, *AcceptInviteReq) (*BasicResp, error)
	// Rules
	AddGroupRule(context.Context, *GroupRuleReq) (*GroupRuleResp, error)
	UpdateGroupRule(context.Context, *GroupRuleReq) (*GroupRuleResp, error)
	DeleteGroupRule(context.Context, *GroupRuleActionReq) (*BasicResp, error)
	// Authorization
	Authorize(context.Context, *AuthorizeGroupReq) (*AuthorizeGroupResp, error)
	mustEmbedUnimplementedGroupServiceServer()
}

// UnimplementedGroupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupServiceServer struct{}

func (UnimplementedGroupServiceServer) CreateGroup(context.Context, *CreateGroupReq) (*GroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedGroupServiceServer) UpdateGroup(context.Context, *UpdateGroupReq) (*GroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedGroupServiceServer) DeleteGroup(context.Context, *GroupActionReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedGroupServiceServer) PublishGroup(context.Context, *GroupActionReq) (*GroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishGroup not implemented")
}
func (UnimplementedGroupServiceServer) GetGroup(context.Context, *GetGroupReq) (*GroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedGroupServiceServer) ListGroups(context.Context, *ListGroupsReq) (*ListGroupsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedGroupServiceServer) GetUserGroups(context.Context, *ListGroupsReq) (*ListGroupsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserGroups not implemented")
}
func (UnimplementedGroupServiceServer) JoinGroup(context.Context, *JoinGroupReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinGroup not implemented")
}
func (UnimplementedGroupServiceServer) LeaveGroup(context.Context, *GroupActionReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (UnimplementedGroupServiceServer) ListMembers(context.Context, *ListGroupMembersReq) (*ListGroupMembersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedGroupServiceServer) UpdateMemberRole(context.Context, *UpdateMemberRoleReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMemberRole not implemented")
}
func (UnimplementedGroupServiceServer) RemoveMember(context.Context, *UpdateMemberRoleReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedGroupServiceServer) BanMember(context.Context, *UpdateMemberRoleReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BanMember not implemented")
}
func (UnimplementedGroupServiceServer) ApproveJoinRequest(context.Context, *JoinDecisionReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveJoinRequest not implemented")
}
func (UnimplementedGroupServiceServer) RejectJoinRequest(context.Context, *JoinDecisionReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectJoinRequest not implemented")
}
func (UnimplementedGroupServiceServer) AddMember(context.Context, *AddMemberReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMember not implemented")
}
func (UnimplementedGroupServiceServer) CreateInvite(context.Context, *CreateInviteReq) (*InviteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInvite not implemented")
}
func (UnimplementedGroupServiceServer) ListInvites(context.Context, *ListInvitesReq) (*ListInvitesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInvites not implemented")
}
func (UnimplementedGroupServiceServer) RevokeInvite(context.Context, *RevokeInviteReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeInvite not implemented")
}
func (UnimplementedGroupServiceServer) GetInvite(context.Context, *GetInviteReq) (*InviteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInvite not implemented")
}
func (UnimplementedGroupServiceServer) AcceptInvite(context.Context, *AcceptInviteReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptInvite not implemented")
}
func (UnimplementedGroupServiceServer) AddGroupRule(context.Context, *GroupRuleReq) (*GroupRuleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGroupRule not implemented")
}
func (UnimplementedGroupServiceServer) UpdateGroupRule(context.Context, *GroupRuleReq) (*GroupRuleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroupRule not implemented")
}
func (UnimplementedGroupServiceServer) DeleteGroupRule(context.Context, *GroupRuleActionReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGroupRule not implemented")
}
func (UnimplementedGroupServiceServer) Authorize(context.Context, *AuthorizeGroupReq) (*AuthorizeGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedGroupServiceServer) mustEmbedUnimplementedGroupServiceServer() {}
func (UnimplementedGroupServiceServer) testEmbeddedByValue()                      {}

// UnsafeGroupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupServiceServer will
// result in compilation errors.
type UnsafeGroupServiceServer interface {
	mustEmbedUnimplementedGroupServiceServer()
}

func RegisterGroupServiceServer(s grpc.ServiceRegistrar, srv GroupServiceServer) {
	// If the following call panics, it indicates UnimplementedGroupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroupService_ServiceDesc, srv)
}

func _GroupService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).CreateGroup(ctx, req.(*CreateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).UpdateGroup(ctx, req.(*UpdateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).DeleteGroup(ctx, req.(*GroupActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_PublishGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).PublishGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_PublishGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).PublishGroup(ctx, req.(*GroupActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetGroup(ctx, req.(*GetGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListGroups(ctx, req.(*ListGroupsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetUserGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetUserGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetUserGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetUserGroups(ctx, req.(*ListGroupsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_JoinGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).JoinGroup(ctx, req.(*JoinGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_LeaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).LeaveGroup(ctx, req.(*GroupActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListMembers(ctx, req.(*ListGroupMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_UpdateMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).UpdateMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_UpdateMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).UpdateMemberRole(ctx, req.(*UpdateMemberRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).RemoveMember(ctx, req.(*UpdateMemberRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_BanMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).BanMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_BanMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).BanMember(ctx, req.(*UpdateMemberRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ApproveJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinDecisionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ApproveJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ApproveJoinRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ApproveJoinRequest(ctx, req.(*JoinDecisionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_RejectJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinDecisionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).RejectJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_RejectJoinRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).RejectJoinRequest(ctx, req.(*JoinDecisionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_AddMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).AddMember(ctx, req.(*AddMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_CreateInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInviteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).CreateInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_CreateInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).CreateInvite(ctx, req.(*CreateInviteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ListInvites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvitesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListInvites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ListInvites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListInvites(ctx, req.(*ListInvitesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_RevokeInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeInviteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).RevokeInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_RevokeInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).RevokeInvite(ctx, req.(*RevokeInviteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetInvite(ctx, req.(*GetInviteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_AcceptInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptInviteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).AcceptInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_AcceptInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).AcceptInvite(ctx, req.(*AcceptInviteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_AddGroupRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRuleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).AddGroupRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_AddGroupRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).AddGroupRule(ctx, req.(*GroupRuleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_UpdateGroupRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRuleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).UpdateGroupRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_UpdateGroupRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).UpdateGroupRule(ctx, req.(*GroupRuleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_DeleteGroupRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRuleActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).DeleteGroupRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_DeleteGroupRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).DeleteGroupRule(ctx, req.(*GroupRuleActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).Authorize(ctx, req.(*AuthorizeGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupService_ServiceDesc is the grpc.ServiceDesc for GroupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "group_svc.GroupService",
	HandlerType: (*GroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _GroupService_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _GroupService_UpdateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _GroupService_DeleteGroup_Handler,
		},
		{
			MethodName: "PublishGroup",
			Handler:    _GroupService_PublishGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _GroupService_GetGroup_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _GroupService_ListGroups_Handler,
		},
		{
			MethodName: "GetUserGroups",
			Handler:    _GroupService_GetUserGroups_Handler,
		},
		{
			MethodName: "JoinGroup",
			Handler:    _GroupService_JoinGroup_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _GroupService_LeaveGroup_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _GroupService_ListMembers_Handler,
		},
		{
			MethodName: "UpdateMemberRole",
			Handler:    _GroupService_UpdateMemberRole_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _GroupService_RemoveMember_Handler,
		},
		{
			MethodName: "BanMember",
			Handler:    _GroupService_BanMember_Handler,
		},
		{
			MethodName: "ApproveJoinRequest",
			Handler:    _GroupService_ApproveJoinRequest_Handler,
		},
		{
			MethodName: "RejectJoinRequest",
			Handler:    _GroupService_RejectJoinRequest_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _GroupService_AddMember_Handler,
		},
		{
			MethodName: "CreateInvite",
			Handler:    _GroupService_CreateInvite_Handler,
		},
		{
			MethodName: "ListInvites",
			Handler:    _GroupService_ListInvites_Handler,
		},
		{
			MethodName: "RevokeInvite",
			Handler:    _GroupService_RevokeInvite_Handler,
		},
		{
			MethodName: "GetInvite",
			Handler:    _GroupService_GetInvite_Handler,
		},
		{
			MethodName: "AcceptInvite",
			Handler:    _GroupService_AcceptInvite_Handler,
		},
		{
			MethodName: "AddGroupRule",
			Handler:    _GroupService_AddGroupRule_Handler,
		},
		{
			MethodName: "UpdateGroupRule",
			Handler:    _GroupService_UpdateGroupRule_Handler,
		},
		{
			MethodName: "DeleteGroupRule",
			Handler:    _GroupService_DeleteGroupRule_Handler,
		},
		{
			MethodName: "Authorize",
			Handler:    _GroupService_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis/serviceconn/gateway_group/pb/gw_group.proto",
}
