// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: apis/serviceconn/gateway_event/pb/gw_event.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_CreateEvent_FullMethodName            = "/event_svc.EventService/CreateEvent"
	EventService_UpdateEvent_FullMethodName            = "/event_svc.EventService/UpdateEvent"
	EventService_DeleteEvent_FullMethodName            = "/event_svc.EventService/DeleteEvent"
	EventService_PublishEvent_FullMethodName           = "/event_svc.EventService/PublishEvent"
	EventService_CancelEvent_FullMethodName            = "/event_svc.EventService/CancelEvent"
	EventService_GetEvent_FullMethodName               = "/event_svc.EventService/GetEvent"
	EventService_ListEvents_FullMethodName             = "/event_svc.EventService/ListEvents"
	EventService_GetUserEvents_FullMethodName          = "/event_svc.EventService/GetUserEvents"
	EventService_GetUserAttendingEvents_FullMethodName = "/event_svc.EventService/GetUserAttendingEvents"
	EventService_GetGroupEvents_FullMethodName         = "/event_svc.EventService/GetGroupEvents"
	EventService_CreateTicketTier_FullMethodName       = "/event_svc.EventService/CreateTicketTier"
	EventService_UpdateTicketTier_FullMethodName       = "/event_svc.EventService/UpdateTicketTier"
	EventService_DeleteTicketTier_FullMethodName       = "/event_svc.EventService/DeleteTicketTier"
	EventService_CreateCoupon_FullMethodName           = "/event_svc.EventService/CreateCoupon"
	EventService_ListCoupons_FullMethodName            = "/event_svc.EventService/ListCoupons"
	EventService_DeleteCoupon_FullMethodName           = "/event_svc.EventService/DeleteCoupon"
	EventService_ValidateCoupon_FullMethodName         = "/event_svc.EventService/ValidateCoupon"
	EventService_RSVPEvent_FullMethodName              = "/event_svc.EventService/RSVPEvent"
	EventService_CancelRSVP_FullMethodName             = "/event_svc.EventService/CancelRSVP"
	EventService_ProcessPaymentWebhook_FullMethodName  = "/event_svc.EventService/ProcessPaymentWebhook"
	EventService_GetAttendees_FullMethodName           = "/event_svc.EventService/GetAttendees"
	EventService_UpdateAttendance_FullMethodName       = "/event_svc.EventService/UpdateAttendance"
	EventService_SaveEvent_FullMethodName              = "/event_svc.EventService/SaveEvent"
	EventService_UnsaveEvent_FullMethodName            = "/event_svc.EventService/UnsaveEvent"
	EventService_AddEventComment_FullMethodName        = "/event_svc.EventService/AddEventComment"
	EventService_ListEventComments_FullMethodName      = "/event_svc.EventService/ListEventComments"
	EventService_DeleteEventComment_FullMethodName     = "/event_svc.EventService/DeleteEventComment"
	EventService_ReactToEvent_FullMethodName           = "/event_svc.EventService/ReactToEvent"
	EventService_RemoveReaction_FullMethodName         = "/event_svc.EventService/RemoveReaction"
	EventService_ReportEvent_FullMethodName            = "/event_svc.EventService/ReportEvent"
	EventService_AddCoHost_FullMethodName              = "/event_svc.EventService/AddCoHost"
	EventService_RemoveCoHost_FullMethodName           = "/event_svc.EventService/RemoveCoHost"
	EventService_GetCalendarFile_FullMethodName        = "/event_svc.EventService/GetCalendarFile"
	EventService_Authorize_FullMethodName              = "/event_svc.EventService/Authorize"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	// Event CRUD
	CreateEvent(ctx context.Context, in *CreateEventReq, opts ...grpc.CallOption) (*EventResp, error)
	UpdateEvent(ctx context.Context, in *UpdateEventReq, opts ...grpc.CallOption) (*EventResp, error)
	DeleteEvent(ctx context.Context, in *EventActionReq, opts ...grpc.CallOption) (*BasicResp, error)
	PublishEvent(ctx context.Context, in *EventActionReq, opts ...grpc.CallOption) (*EventResp, error)
	CancelEvent(ctx context.Context, in *EventActionReq, opts ...grpc.CallOption) (*EventResp, error)
	GetEvent(ctx context.Context, in *GetEventReq, opts ...grpc.CallOption) (*EventResp, error)
	ListEvents(ctx context.Context, in *ListEventsReq, opts ...grpc.CallOption) (*ListEventsResp, error)
	GetUserEvents(ctx context.Context, in *ListEventsReq, opts ...grpc.CallOption) (*ListEventsResp, error)
	GetUserAttendingEvents(ctx context.Context, in *ListEventsReq, opts ...grpc.CallOption) (*ListEventsResp, error)
	GetGroupEvents(ctx context.Context, in *ListEventsReq, opts ...grpc.CallOption) (*ListEventsResp, error)
	// Ticket Tiers
	CreateTicketTier(ctx context.Context, in *CreateTicketTierReq, opts ...grpc.CallOption) (*TicketTierResp, error)
	UpdateTicketTier(ctx context.Context, in *UpdateTicketTierReq, opts ...grpc.CallOption) (*TicketTierResp, error)
	DeleteTicketTier(ctx context.Context, in *TierActionReq, opts ...grpc.CallOption) (*BasicResp, error)
	// Coupons
	CreateCoupon(ctx context.Context, in *CreateCouponReq, opts ...grpc.CallOption) (*CouponResp, error)
	ListCoupons(ctx context.Context, in *ListCouponsReq, opts ...grpc.CallOption) (*ListCouponsResp, error)
	DeleteCoupon(ctx context.Context, in *CouponActionReq, opts ...grpc.CallOption) (*BasicResp, error)
	ValidateCoupon(ctx context.Context, in *ValidateCouponReq, opts ...grpc.CallOption) (*CouponResp, error)
	// RSVP & Payments
	RSVPEvent(ctx context.Context, in *RSVPReq, opts ...grpc.CallOption) (*RSVPResp, error)
	CancelRSVP(ctx context.Context, in *CancelRSVPReq, opts ...grpc.CallOption) (*BasicResp, error)
	ProcessPaymentWebhook(ctx context.Context, in *PaymentWebhookReq, opts ...grpc.CallOption) (*BasicResp, error)
	// Attendees
	GetAttendees(ctx context.Context, in *ListAttendeesReq, opts ...grpc.CallOption) (*ListAttendeesResp, error)
	UpdateAttendance(ctx context.Context, in *UpdateAttendanceReq, opts ...grpc.CallOption) (*BasicResp, error)
	// Saves / bookmarks
	SaveEvent(ctx context.Context, in *SaveEventReq, opts ...grpc.CallOption) (*BasicResp, error)
	UnsaveEvent(ctx context.Context, in *SaveEventReq, opts ...grpc.CallOption) (*BasicResp, error)
	// Social
	AddEventComment(ctx context.Context, in *AddCommentReq, opts ...grpc.CallOption) (*CommentResp, error)
	ListEventComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error)
	DeleteEventComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*BasicResp, error)
	ReactToEvent(ctx context.Context, in *ReactReq, opts ...grpc.CallOption) (*BasicResp, error)
	RemoveReaction(ctx context.Context, in *ReactReq, opts ...grpc.CallOption) (*BasicResp, error)
	ReportEvent(ctx context.Context, in *ReportEventReq, opts ...grpc.CallOption) (*BasicResp, error)
	// Co-Hosts
	AddCoHost(ctx context.Context, in *CoHostReq, opts ...grpc.CallOption) (*BasicResp, error)
	RemoveCoHost(ctx context.Context, in *CoHostReq, opts ...grpc.CallOption) (*BasicResp, error)
	// Utility
	GetCalendarFile(ctx context.Context, in *CalendarReq, opts ...grpc.CallOption) (*CalendarResp, error)
	// Authorization
	Authorize(ctx context.Context, in *AuthorizeReq, opts ...grpc.CallOption) (*AuthorizeResp, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) CreateEvent(ctx context.Context, in *CreateEventReq, opts ...grpc.CallOption) (*EventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResp)
	err := c.cc.Invoke(ctx, EventService_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateEvent(ctx context.Context, in *UpdateEventReq, opts ...grpc.CallOption) (*EventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResp)
	err := c.cc.Invoke(ctx, EventService_UpdateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteEvent(ctx context.Context, in *EventActionReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_DeleteEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) PublishEvent(ctx context.Context, in *EventActionReq, opts ...grpc.CallOption) (*EventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResp)
	err := c.cc.Invoke(ctx, EventService_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) CancelEvent(ctx context.Context, in *EventActionReq, opts ...grpc.CallOption) (*EventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResp)
	err := c.cc.Invoke(ctx, EventService_CancelEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEvent(ctx context.Context, in *GetEventReq, opts ...grpc.CallOption) (*EventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResp)
	err := c.cc.Invoke(ctx, EventService_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ListEvents(ctx context.Context, in *ListEventsReq, opts ...grpc.CallOption) (*ListEventsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResp)
	err := c.cc.Invoke(ctx, EventService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetUserEvents(ctx context.Context, in *ListEventsReq, opts ...grpc.CallOption) (*ListEventsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResp)
	err := c.cc.Invoke(ctx, EventService_GetUserEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetUserAttendingEvents(ctx context.Context, in *ListEventsReq, opts ...grpc.CallOption) (*ListEventsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResp)
	err := c.cc.Invoke(ctx, EventService_GetUserAttendingEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetGroupEvents(ctx context.Context, in *ListEventsReq, opts ...grpc.CallOption) (*ListEventsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResp)
	err := c.cc.Invoke(ctx, EventService_GetGroupEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) CreateTicketTier(ctx context.Context, in *CreateTicketTierReq, opts ...grpc.CallOption) (*TicketTierResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketTierResp)
	err := c.cc.Invoke(ctx, EventService_CreateTicketTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateTicketTier(ctx context.Context, in *UpdateTicketTierReq, opts ...grpc.CallOption) (*TicketTierResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketTierResp)
	err := c.cc.Invoke(ctx, EventService_UpdateTicketTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteTicketTier(ctx context.Context, in *TierActionReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_DeleteTicketTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) CreateCoupon(ctx context.Context, in *CreateCouponReq, opts ...grpc.CallOption) (*CouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponResp)
	err := c.cc.Invoke(ctx, EventService_CreateCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ListCoupons(ctx context.Context, in *ListCouponsReq, opts ...grpc.CallOption) (*ListCouponsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCouponsResp)
	err := c.cc.Invoke(ctx, EventService_ListCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteCoupon(ctx context.Context, in *CouponActionReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_DeleteCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ValidateCoupon(ctx context.Context, in *ValidateCouponReq, opts ...grpc.CallOption) (*CouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponResp)
	err := c.cc.Invoke(ctx, EventService_ValidateCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) RSVPEvent(ctx context.Context, in *RSVPReq, opts ...grpc.CallOption) (*RSVPResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RSVPResp)
	err := c.cc.Invoke(ctx, EventService_RSVPEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) CancelRSVP(ctx context.Context, in *CancelRSVPReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_CancelRSVP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ProcessPaymentWebhook(ctx context.Context, in *PaymentWebhookReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_ProcessPaymentWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetAttendees(ctx context.Context, in *ListAttendeesReq, opts ...grpc.CallOption) (*ListAttendeesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttendeesResp)
	err := c.cc.Invoke(ctx, EventService_GetAttendees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateAttendance(ctx context.Context, in *UpdateAttendanceReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_UpdateAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SaveEvent(ctx context.Context, in *SaveEventReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_SaveEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UnsaveEvent(ctx context.Context, in *SaveEventReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_UnsaveEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) AddEventComment(ctx context.Context, in *AddCommentReq, opts ...grpc.CallOption) (*CommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResp)
	err := c.cc.Invoke(ctx, EventService_AddEventComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ListEventComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResp)
	err := c.cc.Invoke(ctx, EventService_ListEventComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteEventComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_DeleteEventComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ReactToEvent(ctx context.Context, in *ReactReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_ReactToEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) RemoveReaction(ctx context.Context, in *ReactReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_RemoveReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ReportEvent(ctx context.Context, in *ReportEventReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_ReportEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) AddCoHost(ctx context.Context, in *CoHostReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_AddCoHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) RemoveCoHost(ctx context.Context, in *CoHostReq, opts ...grpc.CallOption) (*BasicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResp)
	err := c.cc.Invoke(ctx, EventService_RemoveCoHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetCalendarFile(ctx context.Context, in *CalendarReq, opts ...grpc.CallOption) (*CalendarResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalendarResp)
	err := c.cc.Invoke(ctx, EventService_GetCalendarFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Authorize(ctx context.Context, in *AuthorizeReq, opts ...grpc.CallOption) (*AuthorizeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResp)
	err := c.cc.Invoke(ctx, EventService_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
type EventServiceServer interface {
	// Event CRUD
	CreateEvent(context.Context, *CreateEventReq) (*EventResp, error)
	UpdateEvent(context.Context, *UpdateEventReq) (*EventResp, error)
	DeleteEvent(context.Context, *EventActionReq) (*BasicResp, error)
	PublishEvent(context.Context, *EventActionReq) (*EventResp, error)
	CancelEvent(context.Context, *EventActionReq) (*EventResp, error)
	GetEvent(context.Context, *GetEventReq) (*EventResp, error)
	ListEvents(context.Context, *ListEventsReq) (*ListEventsResp, error)
	GetUserEvents(context.Context, *ListEventsReq) (*ListEventsResp, error)
	GetUserAttendingEvents(context.Context, *ListEventsReq) (*ListEventsResp, error)
	GetGroupEvents(context.Context, *ListEventsReq) (*ListEventsResp, error)
	// Ticket Tiers
	CreateTicketTier(context.Context, *CreateTicketTierReq) (*TicketTierResp, error)
	UpdateTicketTier(context.Context, *UpdateTicketTierReq) (*TicketTierResp, error)
	DeleteTicketTier(context.Context, *TierActionReq) (*BasicResp, error)
	// Coupons
	CreateCoupon(context.Context, *CreateCouponReq) (*CouponResp, error)
	ListCoupons(context.Context, *ListCouponsReq) (*ListCouponsResp, error)
	DeleteCoupon(context.Context, *CouponActionReq) (*BasicResp, error)
	ValidateCoupon(context.Context, *ValidateCouponReq) (*CouponResp, error)
	// RSVP & Payments
	RSVPEvent(context.Context, *RSVPReq) (*RSVPResp, error)
	CancelRSVP(context.Context, *CancelRSVPReq) (*BasicResp, error)
	ProcessPaymentWebhook(context.Context, *PaymentWebhookReq) (*BasicResp, error)
	// Attendees
	GetAttendees(context.Context, *ListAttendeesReq) (*ListAttendeesResp, error)
	UpdateAttendance(context.Context, *UpdateAttendanceReq) (*BasicResp, error)
	// Saves / bookmarks
	SaveEvent(context.Context, *SaveEventReq) (*BasicResp, error)
	UnsaveEvent(context.Context, *SaveEventReq) (*BasicResp, error)
	// Social
	AddEventComment(context.Context, *AddCommentReq) (*CommentResp, error)
	ListEventComments(context.Context, *ListCommentsReq) (*ListCommentsResp, error)
	DeleteEventComment(context.Context, *DeleteCommentReq) (*BasicResp, error)
	ReactToEvent(context.Context, *ReactReq) (*BasicResp, error)
	RemoveReaction(context.Context, *ReactReq) (*BasicResp, error)
	ReportEvent(context.Context, *ReportEventReq) (*BasicResp, error)
	// Co-Hosts
	AddCoHost(context.Context, *CoHostReq) (*BasicResp, error)
	RemoveCoHost(context.Context, *CoHostReq) (*BasicResp, error)
	// Utility
	GetCalendarFile(context.Context, *CalendarReq) (*CalendarResp, error)
	// Authorization
	Authorize(context.Context, *AuthorizeReq) (*AuthorizeResp, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) CreateEvent(context.Context, *CreateEventReq) (*EventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedEventServiceServer) UpdateEvent(context.Context, *UpdateEventReq) (*EventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (UnimplementedEventServiceServer) DeleteEvent(context.Context, *EventActionReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedEventServiceServer) PublishEvent(context.Context, *EventActionReq) (*EventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedEventServiceServer) CancelEvent(context.Context, *EventActionReq) (*EventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelEvent not implemented")
}
func (UnimplementedEventServiceServer) GetEvent(context.Context, *GetEventReq) (*EventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedEventServiceServer) ListEvents(context.Context, *ListEventsReq) (*ListEventsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedEventServiceServer) GetUserEvents(context.Context, *ListEventsReq) (*ListEventsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserEvents not implemented")
}
func (UnimplementedEventServiceServer) GetUserAttendingEvents(context.Context, *ListEventsReq) (*ListEventsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAttendingEvents not implemented")
}
func (UnimplementedEventServiceServer) GetGroupEvents(context.Context, *ListEventsReq) (*ListEventsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupEvents not implemented")
}
func (UnimplementedEventServiceServer) CreateTicketTier(context.Context, *CreateTicketTierReq) (*TicketTierResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTicketTier not implemented")
}
func (UnimplementedEventServiceServer) UpdateTicketTier(context.Context, *UpdateTicketTierReq) (*TicketTierResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTicketTier not implemented")
}
func (UnimplementedEventServiceServer) DeleteTicketTier(context.Context, *TierActionReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTicketTier not implemented")
}
func (UnimplementedEventServiceServer) CreateCoupon(context.Context, *CreateCouponReq) (*CouponResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCoupon not implemented")
}
func (UnimplementedEventServiceServer) ListCoupons(context.Context, *ListCouponsReq) (*ListCouponsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCoupons not implemented")
}
func (UnimplementedEventServiceServer) DeleteCoupon(context.Context, *CouponActionReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCoupon not implemented")
}
func (UnimplementedEventServiceServer) ValidateCoupon(context.Context, *ValidateCouponReq) (*CouponResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateCoupon not implemented")
}
func (UnimplementedEventServiceServer) RSVPEvent(context.Context, *RSVPReq) (*RSVPResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RSVPEvent not implemented")
}
func (UnimplementedEventServiceServer) CancelRSVP(context.Context, *CancelRSVPReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRSVP not implemented")
}
func (UnimplementedEventServiceServer) ProcessPaymentWebhook(context.Context, *PaymentWebhookReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessPaymentWebhook not implemented")
}
func (UnimplementedEventServiceServer) GetAttendees(context.Context, *ListAttendeesReq) (*ListAttendeesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttendees not implemented")
}
func (UnimplementedEventServiceServer) UpdateAttendance(context.Context, *UpdateAttendanceReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAttendance not implemented")
}
func (UnimplementedEventServiceServer) SaveEvent(context.Context, *SaveEventReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveEvent not implemented")
}
func (UnimplementedEventServiceServer) UnsaveEvent(context.Context, *SaveEventReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsaveEvent not implemented")
}
func (UnimplementedEventServiceServer) AddEventComment(context.Context, *AddCommentReq) (*CommentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddEventComment not implemented")
}
func (UnimplementedEventServiceServer) ListEventComments(context.Context, *ListCommentsReq) (*ListCommentsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEventComments not implemented")
}
func (UnimplementedEventServiceServer) DeleteEventComment(context.Context, *DeleteCommentReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEventComment not implemented")
}
func (UnimplementedEventServiceServer) ReactToEvent(context.Context, *ReactReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReactToEvent not implemented")
}
func (UnimplementedEventServiceServer) RemoveReaction(context.Context, *ReactReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveReaction not implemented")
}
func (UnimplementedEventServiceServer) ReportEvent(context.Context, *ReportEventReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportEvent not implemented")
}
func (UnimplementedEventServiceServer) AddCoHost(context.Context, *CoHostReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCoHost not implemented")
}
func (UnimplementedEventServiceServer) RemoveCoHost(context.Context, *CoHostReq) (*BasicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveCoHost not implemented")
}
func (UnimplementedEventServiceServer) GetCalendarFile(context.Context, *CalendarReq) (*CalendarResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCalendarFile not implemented")
}
func (UnimplementedEventServiceServer) Authorize(context.Context, *AuthorizeReq) (*AuthorizeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call panics, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateEvent(ctx, req.(*CreateEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateEvent(ctx, req.(*UpdateEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_DeleteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteEvent(ctx, req.(*EventActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).PublishEvent(ctx, req.(*EventActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_CancelEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CancelEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CancelEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CancelEvent(ctx, req.(*EventActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEvent(ctx, req.(*GetEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ListEvents(ctx, req.(*ListEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetUserEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetUserEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetUserEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetUserEvents(ctx, req.(*ListEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetUserAttendingEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetUserAttendingEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetUserAttendingEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetUserAttendingEvents(ctx, req.(*ListEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetGroupEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetGroupEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetGroupEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetGroupEvents(ctx, req.(*ListEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_CreateTicketTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketTierReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateTicketTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateTicketTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateTicketTier(ctx, req.(*CreateTicketTierReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateTicketTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketTierReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateTicketTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateTicketTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateTicketTier(ctx, req.(*UpdateTicketTierReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteTicketTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TierActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteTicketTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_DeleteTicketTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteTicketTier(ctx, req.(*TierActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_CreateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateCoupon(ctx, req.(*CreateCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ListCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ListCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ListCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ListCoupons(ctx, req.(*ListCouponsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_DeleteCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteCoupon(ctx, req.(*CouponActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ValidateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ValidateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ValidateCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ValidateCoupon(ctx, req.(*ValidateCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_RSVPEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSVPReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).RSVPEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_RSVPEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).RSVPEvent(ctx, req.(*RSVPReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_CancelRSVP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRSVPReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CancelRSVP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CancelRSVP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CancelRSVP(ctx, req.(*CancelRSVPReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ProcessPaymentWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentWebhookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ProcessPaymentWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ProcessPaymentWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ProcessPaymentWebhook(ctx, req.(*PaymentWebhookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetAttendees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttendeesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetAttendees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetAttendees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetAttendees(ctx, req.(*ListAttendeesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAttendanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateAttendance(ctx, req.(*UpdateAttendanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SaveEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SaveEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_SaveEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SaveEvent(ctx, req.(*SaveEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UnsaveEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UnsaveEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UnsaveEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UnsaveEvent(ctx, req.(*SaveEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_AddEventComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).AddEventComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_AddEventComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).AddEventComment(ctx, req.(*AddCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ListEventComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ListEventComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ListEventComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ListEventComments(ctx, req.(*ListCommentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteEventComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteEventComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_DeleteEventComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteEventComment(ctx, req.(*DeleteCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ReactToEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ReactToEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ReactToEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ReactToEvent(ctx, req.(*ReactReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_RemoveReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).RemoveReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_RemoveReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).RemoveReaction(ctx, req.(*ReactReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ReportEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ReportEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ReportEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ReportEvent(ctx, req.(*ReportEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_AddCoHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoHostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).AddCoHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_AddCoHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).AddCoHost(ctx, req.(*CoHostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_RemoveCoHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoHostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).RemoveCoHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_RemoveCoHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).RemoveCoHost(ctx, req.(*CoHostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetCalendarFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalendarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetCalendarFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetCalendarFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetCalendarFile(ctx, req.(*CalendarReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Authorize(ctx, req.(*AuthorizeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event_svc.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventService_CreateEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _EventService_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventService_DeleteEvent_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _EventService_PublishEvent_Handler,
		},
		{
			MethodName: "CancelEvent",
			Handler:    _EventService_CancelEvent_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _EventService_GetEvent_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _EventService_ListEvents_Handler,
		},
		{
			MethodName: "GetUserEvents",
			Handler:    _EventService_GetUserEvents_Handler,
		},
		{
			MethodName: "GetUserAttendingEvents",
			Handler:    _EventService_GetUserAttendingEvents_Handler,
		},
		{
			MethodName: "GetGroupEvents",
			Handler:    _EventService_GetGroupEvents_Handler,
		},
		{
			MethodName: "CreateTicketTier",
			Handler:    _EventService_CreateTicketTier_Handler,
		},
		{
			MethodName: "UpdateTicketTier",
			Handler:    _EventService_UpdateTicketTier_Handler,
		},
		{
			MethodName: "DeleteTicketTier",
			Handler:    _EventService_DeleteTicketTier_Handler,
		},
		{
			MethodName: "CreateCoupon",
			Handler:    _EventService_CreateCoupon_Handler,
		},
		{
			MethodName: "ListCoupons",
			Handler:    _EventService_ListCoupons_Handler,
		},
		{
			MethodName: "DeleteCoupon",
			Handler:    _EventService_DeleteCoupon_Handler,
		},
		{
			MethodName: "ValidateCoupon",
			Handler:    _EventService_ValidateCoupon_Handler,
		},
		{
			MethodName: "RSVPEvent",
			Handler:    _EventService_RSVPEvent_Handler,
		},
		{
			MethodName: "CancelRSVP",
			Handler:    _EventService_CancelRSVP_Handler,
		},
		{
			MethodName: "ProcessPaymentWebhook",
			Handler:    _EventService_ProcessPaymentWebhook_Handler,
		},
		{
			MethodName: "GetAttendees",
			Handler:    _EventService_GetAttendees_Handler,
		},
		{
			MethodName: "UpdateAttendance",
			Handler:    _EventService_UpdateAttendance_Handler,
		},
		{
			MethodName: "SaveEvent",
			Handler:    _EventService_SaveEvent_Handler,
		},
		{
			MethodName: "UnsaveEvent",
			Handler:    _EventService_UnsaveEvent_Handler,
		},
		{
			MethodName: "AddEventComment",
			Handler:    _EventService_AddEventComment_Handler,
		},
		{
			MethodName: "ListEventComments",
			Handler:    _EventService_ListEventComments_Handler,
		},
		{
			MethodName: "DeleteEventComment",
			Handler:    _EventService_DeleteEventComment_Handler,
		},
		{
			MethodName: "ReactToEvent",
			Handler:    _EventService_ReactToEvent_Handler,
		},
		{
			MethodName: "RemoveReaction",
			Handler:    _EventService_RemoveReaction_Handler,
		},
		{
			MethodName: "ReportEvent",
			Handler:    _EventService_ReportEvent_Handler,
		},
		{
			MethodName: "AddCoHost",
			Handler:    _EventService_AddCoHost_Handler,
		},
		{
			MethodName: "RemoveCoHost",
			Handler:    _EventService_RemoveCoHost_Handler,
		},
		{
			MethodName: "GetCalendarFile",
			Handler:    _EventService_GetCalendarFile_Handler,
		},
		{
			MethodName: "Authorize",
			Handler:    _EventService_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis/serviceconn/gateway_event/pb/gw_event.proto",
}
